run:
  timeout: "1m"
  issue-exit-code: 1
  tests: false
  skip-dirs-use-default: true
  allow-parallel-runners: true
  go: "1.21"
  skip-files:
    - ".*_string.go"
linters:
  # Disable all linters.
  # Default: false
  # disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable: []
  # Enable all available linters.
  # Default: false
  # enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default
  disable:
    - varnamelen
    - asasalint
    - depguard
    - containedctx
    - gomnd
  
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: false
