apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: summit-assets-pvc
  namespace: summit
  labels:
    app.kubernetes.io/name: summit-assetserver
    app.kubernetes.io/part-of: summit
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 50Gi
