package wow

const GLOBAL_CACHE_MASK uint32 = 0x15

type AccountDataType uint8

const (
	GLOBAL_CONFIG_CACHE AccountDataType = iota
	PER_CHARACTER_CONFIG_CACHE
	GLOBAL_BINDINGS_PER_CACHE
	PER_CHARACTER_BINDINGS_CACHE
	GLOBAL_MACROS_CACHE
	PER_CHARACTER_MACROS_CACHE
	PER_CHARACTER_LAYOUT_CACHE
	PER_CHARACTER_CHAT_CACHE
	NUM_ACCOUNT_DATA_TYPES
)
