// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// AchievementEntry represents the Achievement.dbc file structure.
//
// Format: niixssssssssssssssssxxxxxxxxxxxxxxxxxxiixixxxxxxxxxxxxxxxxxxii
type AchievementEntry struct {
	ID uint32 `dbc:"offset=0"`
	RequiredFaction uint32 `dbc:"offset=1"`
	MapID uint32 `dbc:"offset=2"`
	Field4 LocalizedString `dbc:"offset=4"`
	CategoryId uint32 `dbc:"offset=38"`
	Points uint32 `dbc:"offset=39"`
	Flags uint32 `dbc:"offset=41"`
	Count uint32 `dbc:"offset=60"`
	RefAchievement uint32 `dbc:"offset=61"`
}

// AchievementCategoryEntry represents the AchievementCategory.dbc file structure.
//
// Format: nixxxxxxxxxxxxxxxxxx
type AchievementCategoryEntry struct {
	ID uint32 `dbc:"offset=0"`
	ParentCategory uint32 `dbc:"offset=1"`
}

// AchievementCriteriaEntry represents the AchievementCriteria.dbc file structure.
//
// Format: niiiiiiiixxxxxxxxxxxxxxxxxiiiix
type AchievementCriteriaEntry struct {
	ID uint32 `dbc:"offset=0"`
	ReferredAchievement uint32 `dbc:"offset=1"`
	RequiredType uint32 `dbc:"offset=2"`
	Value1 uint32 `dbc:"offset=3"`
	Value2 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Flags uint32 `dbc:"offset=26"`
	TimedType uint32 `dbc:"offset=27"`
	TimerStartEvent uint32 `dbc:"offset=28"`
	TimeLimit uint32 `dbc:"offset=29"`
}

