// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// AreaGroupEntry represents the AreaGroup.dbc file structure.
//
// Format: niiiiiii
type AreaGroupEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	NextGroup uint32 `dbc:"offset=7"`
}

// AreaPOIEntry represents the AreaPOI.dbc file structure.
//
// Format: niiiiiiiiiiifffixixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxix
type AreaPOIEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	X float32 `dbc:"offset=12"`
	Y float32 `dbc:"offset=13"`
	Z float32 `dbc:"offset=14"`
	MapID uint32 `dbc:"offset=15"`
	ZoneID uint32 `dbc:"offset=17"`
	WorldState uint32 `dbc:"offset=52"`
}

// AreaTableEntry represents the AreaTable.dbc file structure.
//
// Format: niiiixxxxxissssssssssssssssxiiiiixxx
type AreaTableEntry struct {
	ID uint32 `dbc:"offset=0"`
	MapID uint32 `dbc:"offset=1"`
	Zone uint32 `dbc:"offset=2"`
	ExploreFlag uint32 `dbc:"offset=3"`
	Flags uint32 `dbc:"offset=4"`
	AreaLevel uint32 `dbc:"offset=10"`
	Field11 LocalizedString `dbc:"offset=11"`
	Team uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
	Field30 uint32 `dbc:"offset=30"`
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
}

// WMOAreaTableEntry represents the WMOAreaTable.dbc file structure.
//
// Format: niiixxxxxiixxxxxxxxxxxxxxxxx
type WMOAreaTableEntry struct {
	ID uint32 `dbc:"offset=0"`
	WMOID uint32 `dbc:"offset=1"`
	NameIndex uint32 `dbc:"offset=2"`
	ZoneID uint32 `dbc:"offset=3"`
	GroupID uint32 `dbc:"offset=9"`
	AreaID uint32 `dbc:"offset=10"`
}

// WorldMapAreaEntry represents the WorldMapArea.dbc file structure.
//
// Format: xinxffffixx
type WorldMapAreaEntry struct {
	Field1 uint32 `dbc:"offset=1"`
	MapID uint32 `dbc:"offset=2"`
	Left float32 `dbc:"offset=4"`
	Right float32 `dbc:"offset=5"`
	Top float32 `dbc:"offset=6"`
	Bottom float32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
}

// WorldMapOverlayEntry represents the WorldMapOverlay.dbc file structure.
//
// Format: nxiiiixxxxxxxxxxx
type WorldMapOverlayEntry struct {
	ID uint32 `dbc:"offset=0"`
	MapID uint32 `dbc:"offset=2"`
	AreaID uint32 `dbc:"offset=3"`
	AreaID2 uint32 `dbc:"offset=4"`
	AreaID3 uint32 `dbc:"offset=5"`
}

