// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// CreatureDisplayInfoEntry represents the CreatureDisplayInfo.dbc file structure.
//
// Format: nixifxxxxxxxxxxx
type CreatureDisplayInfoEntry struct {
	ID uint32 `dbc:"offset=0"`
	ModelID uint32 `dbc:"offset=1"`
	ExtendedDisplayInfoID uint32 `dbc:"offset=3"`
	Scale float32 `dbc:"offset=4"`
}

// CreatureDisplayInfoExtraEntry represents the CreatureDisplayInfoExtra.dbc file structure.
//
// Format: dixxxxxxxxxxxxxxxxxxx
type CreatureDisplayInfoExtraEntry struct {
	ID uint32 `dbc:"offset=0"`
	DisplayRaceID uint32 `dbc:"offset=1"`
}

// CreatureFamilyEntry represents the CreatureFamily.dbc file structure.
//
// Format: nfifiiiiixssssssssssssssssxx
type CreatureFamilyEntry struct {
	ID uint32 `dbc:"offset=0"`
	MinScale float32 `dbc:"offset=1"`
	MinScaleLevel uint32 `dbc:"offset=2"`
	MaxScale float32 `dbc:"offset=3"`
	MaxScaleLevel uint32 `dbc:"offset=4"`
	SkillLine1 uint32 `dbc:"offset=5"`
	SkillLine2 uint32 `dbc:"offset=6"`
	PetFoodMask uint32 `dbc:"offset=7"`
	PetTalentType uint32 `dbc:"offset=8"`
	Field10 LocalizedString `dbc:"offset=10"`
}

// CreatureModelDataEntry represents the CreatureModelData.dbc file structure.
//
// Format: nixxfxxxxxxxxxfffxxxxxxxxxxx
type CreatureModelDataEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
	Scale float32 `dbc:"offset=4"`
	CollisionWidth float32 `dbc:"offset=14"`
	CollisionHeight float32 `dbc:"offset=15"`
	MountHeight float32 `dbc:"offset=16"`
}

// CreatureSpellDataEntry represents the CreatureSpellData.dbc file structure.
//
// Format: niiiixxxx
type CreatureSpellDataEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
}

// CreatureTypeEntry represents the CreatureType.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxx
type CreatureTypeEntry struct {
	Index0 uint32 `dbc:"offset=0"`
}

