// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// EmotesEntry represents the Emotes.dbc file structure.
//
// Format: nxxiiix
type EmotesEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=3"`
	EmoteType uint32 `dbc:"offset=4"`
	UnitStandState uint32 `dbc:"offset=5"`
}

// EmotesTextEntry represents the EmotesText.dbc file structure.
//
// Format: nxixxxxxxxxxxxxxxxx
type EmotesTextEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field2 uint32 `dbc:"offset=2"`
}

