// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// FactionEntry represents the Faction.dbc file structure.
//
// Format: niiiiiiiiiiiiiiiiiiffixssssssssssssssssxxxxxxxxxxxxxxxxxx
type FactionEntry struct {
	ID uint32 `dbc:"offset=0"`
	ReputationListID uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
	Field16 uint32 `dbc:"offset=16"`
	Field17 uint32 `dbc:"offset=17"`
	Team uint32 `dbc:"offset=18"`
	SpilloverRateIn float32 `dbc:"offset=19"`
	SpilloverRateOut float32 `dbc:"offset=20"`
	SpilloverMaxRankIn uint32 `dbc:"offset=21"`
	Field23 LocalizedString `dbc:"offset=23"`
}

// FactionTemplateEntry represents the FactionTemplate.dbc file structure.
//
// Format: niiiiiiiiiiiii
type FactionTemplateEntry struct {
	ID uint32 `dbc:"offset=0"`
	Faction uint32 `dbc:"offset=1"`
	FactionFlags uint32 `dbc:"offset=2"`
	OurMask uint32 `dbc:"offset=3"`
	FriendlyMask uint32 `dbc:"offset=4"`
	HostileMask uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
}

