// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// GameObjectArtKitEntry represents the GameObjectArtKit.dbc file structure.
//
// Format: nxxxxxxx
type GameObjectArtKitEntry struct {
	ID uint32 `dbc:"offset=0"`
}

// GameObjectDisplayInfoEntry represents the GameObjectDisplayInfo.dbc file structure.
//
// Format: nsxxxxxxxxxxffffffx
type GameObjectDisplayInfoEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 *StringRef `dbc:"offset=1"`
	MaxZ float32 `dbc:"offset=12"`
	Field13 float32 `dbc:"offset=13"`
	Field14 float32 `dbc:"offset=14"`
	Field15 float32 `dbc:"offset=15"`
	Field16 float32 `dbc:"offset=16"`
	Field17 float32 `dbc:"offset=17"`
}

