// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// GtBarberShopCostBaseEntry represents the GtBarberShopCostBase.dbc file structure.
//
// Format: df
type GtBarberShopCostBaseEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtChanceToMeleeCritEntry represents the GtChanceToMeleeCrit.dbc file structure.
//
// Format: df
type GtChanceToMeleeCritEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtChanceToMeleeCritBaseEntry represents the GtChanceToMeleeCritBase.dbc file structure.
//
// Format: df
type GtChanceToMeleeCritBaseEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtChanceToSpellCritEntry represents the GtChanceToSpellCrit.dbc file structure.
//
// Format: df
type GtChanceToSpellCritEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtChanceToSpellCritBaseEntry represents the GtChanceToSpellCritBase.dbc file structure.
//
// Format: df
type GtChanceToSpellCritBaseEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtCombatRatingsEntry represents the GtCombatRatings.dbc file structure.
//
// Format: df
type GtCombatRatingsEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtNPCManaCostScalerEntry represents the GtNPCManaCostScaler.dbc file structure.
//
// Format: df
type GtNPCManaCostScalerEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtOCTClassCombatRatingScalarEntry represents the GtOCTClassCombatRatingScalar.dbc file structure.
//
// Format: df
type GtOCTClassCombatRatingScalarEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtOCTRegenHPEntry represents the GtOCTRegenHP.dbc file structure.
//
// Format: df
type GtOCTRegenHPEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtRegenHPPerSptEntry represents the GtRegenHPPerSpt.dbc file structure.
//
// Format: df
type GtRegenHPPerSptEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// GtRegenMPPerSptEntry represents the GtRegenMPPerSpt.dbc file structure.
//
// Format: df
type GtRegenMPPerSptEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

