// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// ItemEntry represents the Item.dbc file structure.
//
// Format: niiiiiii
type ItemEntry struct {
	ID uint32 `dbc:"offset=0"`
	ClassID uint32 `dbc:"offset=1"`
	SubclassID uint32 `dbc:"offset=2"`
	SoundOverrideSubclassID uint32 `dbc:"offset=3"`
	Material uint32 `dbc:"offset=4"`
	DisplayInfoID uint32 `dbc:"offset=5"`
	InventoryType uint32 `dbc:"offset=6"`
	SheatheType uint32 `dbc:"offset=7"`
}

// ItemBagFamilyEntry represents the ItemBagFamily.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxx
type ItemBagFamilyEntry struct {
	Index0 uint32 `dbc:"offset=0"`
}

// ItemDisplayInfoEntry represents the ItemDisplayInfo.dbc file structure.
//
// Format: nxxxxsxxxxxxxxxxxxxxxxxxx
type ItemDisplayInfoEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field5 *StringRef `dbc:"offset=5"`
}

// ItemExtendedCostEntry represents the ItemExtendedCost.dbc file structure.
//
// Format: niiiiiiiiiiiiiix
type ItemExtendedCostEntry struct {
	ID uint32 `dbc:"offset=0"`
	ReqHonorPoints uint32 `dbc:"offset=1"`
	ReqArenaPoints uint32 `dbc:"offset=2"`
	ReqArenaSlot uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
}

// ItemLimitCategoryEntry represents the ItemLimitCategory.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxii
type ItemLimitCategoryEntry struct {
	ID uint32 `dbc:"offset=0"`
	MaxCount uint32 `dbc:"offset=18"`
	Mode uint32 `dbc:"offset=19"`
}

// ItemRandomPropertiesEntry represents the ItemRandomProperties.dbc file structure.
//
// Format: nxiiiiissssssssssssssssx
type ItemRandomPropertiesEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 LocalizedString `dbc:"offset=7"`
}

// ItemRandomSuffixEntry represents the ItemRandomSuffix.dbc file structure.
//
// Format: nssssssssssssssssxxiiiiiiiiii
type ItemRandomSuffixEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 LocalizedString `dbc:"offset=1"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
}

// ItemSetEntry represents the ItemSet.dbc file structure.
//
// Format: dssssssssssssssssxiiiiiiiiiixxxxxxxiiiiiiiiiiiiiiiiii
type ItemSetEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 LocalizedString `dbc:"offset=1"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field35 uint32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Field37 uint32 `dbc:"offset=37"`
	Field38 uint32 `dbc:"offset=38"`
	Field39 uint32 `dbc:"offset=39"`
	Field40 uint32 `dbc:"offset=40"`
	Field41 uint32 `dbc:"offset=41"`
	Field42 uint32 `dbc:"offset=42"`
	Field43 uint32 `dbc:"offset=43"`
	Field44 uint32 `dbc:"offset=44"`
	Field45 uint32 `dbc:"offset=45"`
	Field46 uint32 `dbc:"offset=46"`
	Field47 uint32 `dbc:"offset=47"`
	Field48 uint32 `dbc:"offset=48"`
	Field49 uint32 `dbc:"offset=49"`
	Field50 uint32 `dbc:"offset=50"`
	Field51 uint32 `dbc:"offset=51"`
	Field52 uint32 `dbc:"offset=52"`
}

