// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// DungeonEncounterEntry represents the DungeonEncounter.dbc file structure.
//
// Format: niixissssssssssssssssxx
type DungeonEncounterEntry struct {
	ID uint32 `dbc:"offset=0"`
	MapID uint32 `dbc:"offset=1"`
	Difficulty uint32 `dbc:"offset=2"`
	EncounterIndex uint32 `dbc:"offset=4"`
	Field5 LocalizedString `dbc:"offset=5"`
}

// LFGDungeonEntry represents the LFGDungeon.dbc file structure.
//
// Format: nssssssssssssssssxiiiiiiiiixxixixxxxxxxxxxxxxxxxx
type LFGDungeonEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 LocalizedString `dbc:"offset=1"`
	MinLevel uint32 `dbc:"offset=18"`
	MaxLevel uint32 `dbc:"offset=19"`
	TargetLevel uint32 `dbc:"offset=20"`
	TargetLevelMin uint32 `dbc:"offset=21"`
	TargetLevelMax uint32 `dbc:"offset=22"`
	MapID uint32 `dbc:"offset=23"`
	Difficulty uint32 `dbc:"offset=24"`
	Flags uint32 `dbc:"offset=25"`
	TypeID uint32 `dbc:"offset=26"`
	ExpansionLevel uint32 `dbc:"offset=29"`
	GroupID uint32 `dbc:"offset=31"`
}

