// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// LightEntry represents the Light.dbc file structure.
//
// Format: nifffxxxxxxxxxx
type LightEntry struct {
	ID uint32 `dbc:"offset=0"`
	MapID uint32 `dbc:"offset=1"`
	X float32 `dbc:"offset=2"`
	Y float32 `dbc:"offset=3"`
	Z float32 `dbc:"offset=4"`
}

// LiquidTypeEntry represents the LiquidType.dbc file structure.
//
// Format: nxxixixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type LiquidTypeEntry struct {
	ID uint32 `dbc:"offset=0"`
	Type uint32 `dbc:"offset=3"`
	SpellID uint32 `dbc:"offset=5"`
}

