// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// MailTemplateEntry represents the MailTemplate.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxssssssssssssssssx
type MailTemplateEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field18 LocalizedString `dbc:"offset=18"`
}

