// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// MapEntry represents the Map.dbc file structure.
//
// Format: nxiixssssssssssssssssxixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxixiffxixi
type MapEntry struct {
	ID uint32 `dbc:"offset=0"`
	InstanceType uint32 `dbc:"offset=2"`
	Flags uint32 `dbc:"offset=3"`
	Field5 LocalizedString `dbc:"offset=5"`
	LinkedZone uint32 `dbc:"offset=22"`
	MultimapID uint32 `dbc:"offset=57"`
	EntranceMap uint32 `dbc:"offset=59"`
	EntranceX float32 `dbc:"offset=60"`
	EntranceY float32 `dbc:"offset=61"`
	ExpansionID uint32 `dbc:"offset=63"`
	MaxPlayers uint32 `dbc:"offset=65"`
}

// MapDifficultyEntry represents the MapDifficulty.dbc file structure.
//
// Format: diisxxxxxxxxxxxxxxxxiix
type MapDifficultyEntry struct {
	ID uint32 `dbc:"offset=0"`
	MapID uint32 `dbc:"offset=1"`
	Difficulty uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"` // string offset
	ResetTime uint32 `dbc:"offset=20"`
	MaxPlayers uint32 `dbc:"offset=21"`
}

