// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// BankBagSlotPricesEntry represents the BankBagSlotPrices.dbc file structure.
//
// Format: ni
type BankBagSlotPricesEntry struct {
	ID uint32 `dbc:"offset=0"`
	Price uint32 `dbc:"offset=1"`
}

// BarberShopStyleEntry represents the BarberShopStyle.dbc file structure.
//
// Format: nixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiii
type BarberShopStyleEntry struct {
	ID uint32 `dbc:"offset=0"`
	Type uint32 `dbc:"offset=1"`
	Race uint32 `dbc:"offset=37"`
	Gender uint32 `dbc:"offset=38"`
	HairID uint32 `dbc:"offset=39"`
}

// BattlemasterListEntry represents the BattlemasterList.dbc file structure.
//
// Format: niiiiiiiiixssssssssssssssssxiixx
type BattlemasterListEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Type uint32 `dbc:"offset=9"`
	Field11 LocalizedString `dbc:"offset=11"`
	MaxGroupSize uint32 `dbc:"offset=28"`
	HolidayID uint32 `dbc:"offset=29"`
}

// ChatChannelsEntry represents the ChatChannels.dbc file structure.
//
// Format: nixssssssssssssssssxxxxxxxxxxxxxxxxxx
type ChatChannelsEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
	Field3 LocalizedString `dbc:"offset=3"`
}

// CinematicCameraEntry represents the CinematicCamera.dbc file structure.
//
// Format: nsiffff
type CinematicCameraEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 *StringRef `dbc:"offset=1"`
	SoundID uint32 `dbc:"offset=2"`
	OriginX float32 `dbc:"offset=3"`
	OriginY float32 `dbc:"offset=4"`
	OriginZ float32 `dbc:"offset=5"`
	OriginFacing float32 `dbc:"offset=6"`
}

// CinematicSequencesEntry represents the CinematicSequences.dbc file structure.
//
// Format: nxixxxxxxx
type CinematicSequencesEntry struct {
	ID uint32 `dbc:"offset=0"`
	CameraID uint32 `dbc:"offset=2"`
}

// CurrencyTypesEntry represents the CurrencyTypes.dbc file structure.
//
// Format: xnxi
type CurrencyTypesEntry struct {
	ItemID uint32 `dbc:"offset=1"`
	BitIndex uint32 `dbc:"offset=3"`
}

// DestructibleModelDataEntry represents the DestructibleModelData.dbc file structure.
//
// Format: nxxixxxixxxixxxixxx
type DestructibleModelDataEntry struct {
	ID uint32 `dbc:"offset=0"`
	DamagedDisplayID uint32 `dbc:"offset=3"`
	DestroyedDisplayID uint32 `dbc:"offset=7"`
	RebuildingDisplayID uint32 `dbc:"offset=11"`
	SmokeDisplayID uint32 `dbc:"offset=15"`
}

// DurabilityCostsEntry represents the DurabilityCosts.dbc file structure.
//
// Format: niiiiiiiiiiiiiiiiiiiiiiiiiiiii
type DurabilityCostsEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
	Field16 uint32 `dbc:"offset=16"`
	Field17 uint32 `dbc:"offset=17"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
}

// DurabilityQualityEntry represents the DurabilityQuality.dbc file structure.
//
// Format: nf
type DurabilityQualityEntry struct {
	ID uint32 `dbc:"offset=0"`
	QualityMod float32 `dbc:"offset=1"`
}

// GemPropertiesEntry represents the GemProperties.dbc file structure.
//
// Format: nixxi
type GemPropertiesEntry struct {
	ID uint32 `dbc:"offset=0"`
	EnchantmentID uint32 `dbc:"offset=1"`
	Field4 uint32 `dbc:"offset=4"`
}

// GlyphPropertiesEntry represents the GlyphProperties.dbc file structure.
//
// Format: niix
type GlyphPropertiesEntry struct {
	ID uint32 `dbc:"offset=0"`
	SpellID uint32 `dbc:"offset=1"`
	TypeFlags uint32 `dbc:"offset=2"`
}

// GlyphSlotEntry represents the GlyphSlot.dbc file structure.
//
// Format: nii
type GlyphSlotEntry struct {
	ID uint32 `dbc:"offset=0"`
	TypeFlags uint32 `dbc:"offset=1"`
	Order uint32 `dbc:"offset=2"`
}

// HolidaysEntry represents the Holidays.dbc file structure.
//
// Format: niiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiixxsiix
type HolidaysEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
	Field16 uint32 `dbc:"offset=16"`
	Field17 uint32 `dbc:"offset=17"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
	Field30 uint32 `dbc:"offset=30"`
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
	Field35 uint32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Region uint32 `dbc:"offset=37"`
	Looping uint32 `dbc:"offset=38"`
	Field39 uint32 `dbc:"offset=39"`
	Field40 uint32 `dbc:"offset=40"`
	Field41 uint32 `dbc:"offset=41"`
	Field42 uint32 `dbc:"offset=42"`
	Field43 uint32 `dbc:"offset=43"`
	Field44 uint32 `dbc:"offset=44"`
	Field45 uint32 `dbc:"offset=45"`
	Field46 uint32 `dbc:"offset=46"`
	Field47 uint32 `dbc:"offset=47"`
	Field48 uint32 `dbc:"offset=48"`
	Field51 *StringRef `dbc:"offset=51"`
	Priority uint32 `dbc:"offset=52"`
	CalendarFilterType uint32 `dbc:"offset=53"`
}

// MovieEntry represents the Movie.dbc file structure.
//
// Format: nxx
type MovieEntry struct {
	ID uint32 `dbc:"offset=0"`
}

// NamesProfanityEntry represents the NamesProfanity.dbc file structure.
//
// Format: xsx
type NamesProfanityEntry struct {
	Field1 uint32 `dbc:"offset=1"` // string offset
}

// NamesReservedEntry represents the NamesReserved.dbc file structure.
//
// Format: xsx
type NamesReservedEntry struct {
	Field1 uint32 `dbc:"offset=1"` // string offset
}

// OverrideSpellDataEntry represents the OverrideSpellData.dbc file structure.
//
// Format: niiiiiiiiiix
type OverrideSpellDataEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
}

// PowerDisplayEntry represents the PowerDisplay.dbc file structure.
//
// Format: nixxxx
type PowerDisplayEntry struct {
	ID uint32 `dbc:"offset=0"`
	PowerType uint32 `dbc:"offset=1"`
}

// PvPDifficultyEntry represents the PvPDifficulty.dbc file structure.
//
// Format: diiiii
type PvPDifficultyEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	MapID uint32 `dbc:"offset=1"`
	BracketID uint32 `dbc:"offset=2"`
	MinLevel uint32 `dbc:"offset=3"`
	MaxLevel uint32 `dbc:"offset=4"`
	Difficulty uint32 `dbc:"offset=5"`
}

// QuestFactionRewardEntry represents the QuestFactionReward.dbc file structure.
//
// Format: niiiiiiiiii
type QuestFactionRewardEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
}

// QuestSortEntry represents the QuestSort.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxx
type QuestSortEntry struct {
	ID uint32 `dbc:"offset=0"`
}

// QuestXPEntry represents the QuestXP.dbc file structure.
//
// Format: niiiiiiiiii
type QuestXPEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
}

// RandomPropertiesPointsEntry represents the RandomPropertiesPoints.dbc file structure.
//
// Format: niiiiiiiiiiiiiii
type RandomPropertiesPointsEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	ItemLevel uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
}

// ScalingStatDistributionEntry represents the ScalingStatDistribution.dbc file structure.
//
// Format: niiiiiiiiiiiiiiiiiiiii
type ScalingStatDistributionEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
	Field16 uint32 `dbc:"offset=16"`
	Field17 uint32 `dbc:"offset=17"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	MaxLevel uint32 `dbc:"offset=21"`
}

// ScalingStatValuesEntry represents the ScalingStatValues.dbc file structure.
//
// Format: iniiiiiiiiiiiiiiiiiiiiii
type ScalingStatValuesEntry struct {
	ID uint32 `dbc:"offset=0"`
	Level uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
	SpellPower uint32 `dbc:"offset=16"`
	SSDMultiplier2 uint32 `dbc:"offset=17"`
	SSDMultiplier3 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
}

// SoundEntriesEntry represents the SoundEntries.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type SoundEntriesEntry struct {
	ID uint32 `dbc:"offset=0"`
}

// StableSlotPricesEntry represents the StableSlotPrices.dbc file structure.
//
// Format: ni
type StableSlotPricesEntry struct {
	ID uint32 `dbc:"offset=0"`
	Price uint32 `dbc:"offset=1"`
}

// SummonPropertiesEntry represents the SummonProperties.dbc file structure.
//
// Format: niiiii
type SummonPropertiesEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
	FactionID uint32 `dbc:"offset=2"`
	Type uint32 `dbc:"offset=3"`
	Slot uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
}

// TeamContributionPointsEntry represents the TeamContributionPoints.dbc file structure.
//
// Format: df
type TeamContributionPointsEntry struct {
	Value uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
}

// TotemCategoryEntry represents the TotemCategory.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxii
type TotemCategoryEntry struct {
	ID uint32 `dbc:"offset=0"`
	TotemCategoryMask uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
}

// TransportAnimationEntry represents the TransportAnimation.dbc file structure.
//
// Format: diifffx
type TransportAnimationEntry struct {
	ID uint32 `dbc:"offset=0"`
	TransportID uint32 `dbc:"offset=1"`
	TimeSeg uint32 `dbc:"offset=2"`
	X float32 `dbc:"offset=3"`
	Y float32 `dbc:"offset=4"`
	Z float32 `dbc:"offset=5"`
}

// TransportRotationEntry represents the TransportRotation.dbc file structure.
//
// Format: diiffff
type TransportRotationEntry struct {
	ID uint32 `dbc:"offset=0"`
	TransportID uint32 `dbc:"offset=1"`
	TimeSeg uint32 `dbc:"offset=2"`
	X float32 `dbc:"offset=3"`
	Y float32 `dbc:"offset=4"`
	Z float32 `dbc:"offset=5"`
	W float32 `dbc:"offset=6"`
}

