// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// SkillLineEntry represents the SkillLine.dbc file structure.
//
// Format: nixssssssssssssssssxxxxxxxxxxxxxxxxxxixxxxxxxxxxxxxxxxxi
type SkillLineEntry struct {
	ID uint32 `dbc:"offset=0"`
	CategoryID uint32 `dbc:"offset=1"`
	Field3 LocalizedString `dbc:"offset=3"`
	SpellIcon uint32 `dbc:"offset=37"`
	CanLink uint32 `dbc:"offset=55"`
}

// SkillLineAbilityEntry represents the SkillLineAbility.dbc file structure.
//
// Format: niiiixxiiiiixx
type SkillLineAbilityEntry struct {
	ID uint32 `dbc:"offset=0"`
	SkillLine uint32 `dbc:"offset=1"`
	Spell uint32 `dbc:"offset=2"`
	RaceMask uint32 `dbc:"offset=3"`
	ClassMask uint32 `dbc:"offset=4"`
	MinSkillLineRank uint32 `dbc:"offset=7"`
	SupercededBySpell uint32 `dbc:"offset=8"`
	AcquireMethod uint32 `dbc:"offset=9"`
	TrivialSkillLineRankHigh uint32 `dbc:"offset=10"`
	TrivialSkillLineRankLow uint32 `dbc:"offset=11"`
}

// SkillRaceClassInfoEntry represents the SkillRaceClassInfo.dbc file structure.
//
// Format: diiiixix
type SkillRaceClassInfoEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	SkillID uint32 `dbc:"offset=1"`
	RaceMask uint32 `dbc:"offset=2"`
	ClassMask uint32 `dbc:"offset=3"`
	Flags uint32 `dbc:"offset=4"`
	SkillTierID uint32 `dbc:"offset=6"`
}

// SkillTiersEntry represents the SkillTiers.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxiiiiiiiiiiiiiiii
type SkillTiersEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field17 uint32 `dbc:"offset=17"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
	Field30 uint32 `dbc:"offset=30"`
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
}

// TalentEntry represents the Talent.dbc file structure.
//
// Format: niiiiiiiixxxxixxixxixxx
type TalentEntry struct {
	ID uint32 `dbc:"offset=0"`
	TabID uint32 `dbc:"offset=1"`
	ClassID uint32 `dbc:"offset=2"`
	Row uint32 `dbc:"offset=3"`
	Col uint32 `dbc:"offset=4"`
	SpellID uint32 `dbc:"offset=5"`
	AltMask uint32 `dbc:"offset=6"`
	DependsOn uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field13 uint32 `dbc:"offset=13"`
	Field16 uint32 `dbc:"offset=16"`
	Field19 uint32 `dbc:"offset=19"`
}

// TalentTabEntry represents the TalentTab.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxxxiiix
type TalentTabEntry struct {
	ID uint32 `dbc:"offset=0"`
	PetTalentMask uint32 `dbc:"offset=20"`
	OrderIndex uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
}

