// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// SpellCastTimeEntry represents the SpellCastTime.dbc file structure.
//
// Format: nixx
type SpellCastTimeEntry struct {
	ID uint32 `dbc:"offset=0"`
	CastTime uint32 `dbc:"offset=1"`
}

// SpellCategoryEntry represents the SpellCategory.dbc file structure.
//
// Format: ni
type SpellCategoryEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
}

// SpellDifficultyEntry represents the SpellDifficulty.dbc file structure.
//
// Format: niiii
type SpellDifficultyEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
}

// SpellDurationEntry represents the SpellDuration.dbc file structure.
//
// Format: niii
type SpellDurationEntry struct {
	ID uint32 `dbc:"offset=0"`
	Duration uint32 `dbc:"offset=1"`
	PerLevel uint32 `dbc:"offset=2"`
	MaxDuration uint32 `dbc:"offset=3"`
}

// SpellEntryEntry represents the SpellEntry.dbc file structure.
//
// Format: niiiiiiiiiiiixixiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifxiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssxssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiiiiiiiiiiixfffxxxiiiiixxfffxx
type SpellEntryEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field14 uint32 `dbc:"offset=14"`
	Field16 uint32 `dbc:"offset=16"`
	Field17 uint32 `dbc:"offset=17"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 uint32 `dbc:"offset=19"`
	Field20 uint32 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
	Field30 uint32 `dbc:"offset=30"`
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
	Field35 uint32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Field37 uint32 `dbc:"offset=37"`
	Field38 uint32 `dbc:"offset=38"`
	Field39 uint32 `dbc:"offset=39"`
	Field40 uint32 `dbc:"offset=40"`
	Field41 uint32 `dbc:"offset=41"`
	Field42 uint32 `dbc:"offset=42"`
	Field43 uint32 `dbc:"offset=43"`
	Field44 uint32 `dbc:"offset=44"`
	Field45 uint32 `dbc:"offset=45"`
	Field46 uint32 `dbc:"offset=46"`
	Field47 float32 `dbc:"offset=47"`
	Field49 uint32 `dbc:"offset=49"`
	Field50 uint32 `dbc:"offset=50"`
	Field51 uint32 `dbc:"offset=51"`
	Field52 uint32 `dbc:"offset=52"`
	Field53 uint32 `dbc:"offset=53"`
	Field54 uint32 `dbc:"offset=54"`
	Field55 uint32 `dbc:"offset=55"`
	Field56 uint32 `dbc:"offset=56"`
	Field57 uint32 `dbc:"offset=57"`
	Field58 uint32 `dbc:"offset=58"`
	Field59 uint32 `dbc:"offset=59"`
	Field60 uint32 `dbc:"offset=60"`
	Field61 uint32 `dbc:"offset=61"`
	Field62 uint32 `dbc:"offset=62"`
	Field63 uint32 `dbc:"offset=63"`
	Field64 uint32 `dbc:"offset=64"`
	Field65 uint32 `dbc:"offset=65"`
	Field66 uint32 `dbc:"offset=66"`
	Field67 uint32 `dbc:"offset=67"`
	Field68 uint32 `dbc:"offset=68"`
	Field69 uint32 `dbc:"offset=69"`
	Field70 uint32 `dbc:"offset=70"`
	Field71 uint32 `dbc:"offset=71"`
	Field72 uint32 `dbc:"offset=72"`
	Field73 uint32 `dbc:"offset=73"`
	Field74 uint32 `dbc:"offset=74"`
	Field75 uint32 `dbc:"offset=75"`
	Field76 uint32 `dbc:"offset=76"`
	Field77 float32 `dbc:"offset=77"`
	Field78 float32 `dbc:"offset=78"`
	Field79 float32 `dbc:"offset=79"`
	Field80 uint32 `dbc:"offset=80"`
	Field81 uint32 `dbc:"offset=81"`
	Field82 uint32 `dbc:"offset=82"`
	Field83 uint32 `dbc:"offset=83"`
	Field84 uint32 `dbc:"offset=84"`
	Field85 uint32 `dbc:"offset=85"`
	Field86 uint32 `dbc:"offset=86"`
	Field87 uint32 `dbc:"offset=87"`
	Field88 uint32 `dbc:"offset=88"`
	Field89 uint32 `dbc:"offset=89"`
	Field90 uint32 `dbc:"offset=90"`
	Field91 uint32 `dbc:"offset=91"`
	Field92 uint32 `dbc:"offset=92"`
	Field93 uint32 `dbc:"offset=93"`
	Field94 uint32 `dbc:"offset=94"`
	Field95 uint32 `dbc:"offset=95"`
	Field96 uint32 `dbc:"offset=96"`
	Field97 uint32 `dbc:"offset=97"`
	Field98 uint32 `dbc:"offset=98"`
	Field99 uint32 `dbc:"offset=99"`
	Field100 uint32 `dbc:"offset=100"`
	Field101 float32 `dbc:"offset=101"`
	Field102 float32 `dbc:"offset=102"`
	Field103 float32 `dbc:"offset=103"`
	Field104 uint32 `dbc:"offset=104"`
	Field105 uint32 `dbc:"offset=105"`
	Field106 uint32 `dbc:"offset=106"`
	Field107 uint32 `dbc:"offset=107"`
	Field108 uint32 `dbc:"offset=108"`
	Field109 uint32 `dbc:"offset=109"`
	Field110 uint32 `dbc:"offset=110"`
	Field111 uint32 `dbc:"offset=111"`
	Field112 uint32 `dbc:"offset=112"`
	Field113 uint32 `dbc:"offset=113"`
	Field114 uint32 `dbc:"offset=114"`
	Field115 uint32 `dbc:"offset=115"`
	Field116 uint32 `dbc:"offset=116"`
	Field117 uint32 `dbc:"offset=117"`
	Field118 uint32 `dbc:"offset=118"`
	Field119 float32 `dbc:"offset=119"`
	Field120 float32 `dbc:"offset=120"`
	Field121 float32 `dbc:"offset=121"`
	Field122 uint32 `dbc:"offset=122"`
	Field123 uint32 `dbc:"offset=123"`
	Field124 uint32 `dbc:"offset=124"`
	Field125 uint32 `dbc:"offset=125"`
	Field126 uint32 `dbc:"offset=126"`
	Field127 uint32 `dbc:"offset=127"`
	Field128 uint32 `dbc:"offset=128"`
	Field129 uint32 `dbc:"offset=129"`
	Field130 uint32 `dbc:"offset=130"`
	Field131 uint32 `dbc:"offset=131"`
	Field132 uint32 `dbc:"offset=132"`
	Field133 uint32 `dbc:"offset=133"`
	Field134 uint32 `dbc:"offset=134"`
	Field135 uint32 `dbc:"offset=135"`
	Field136 LocalizedString `dbc:"offset=136"`
	Field153 LocalizedString `dbc:"offset=153"`
	Field204 uint32 `dbc:"offset=204"`
	Field205 uint32 `dbc:"offset=205"`
	Field206 uint32 `dbc:"offset=206"`
	Field207 uint32 `dbc:"offset=207"`
	Field208 uint32 `dbc:"offset=208"`
	Field209 uint32 `dbc:"offset=209"`
	Field210 uint32 `dbc:"offset=210"`
	Field211 uint32 `dbc:"offset=211"`
	Field212 uint32 `dbc:"offset=212"`
	Field213 uint32 `dbc:"offset=213"`
	Field214 uint32 `dbc:"offset=214"`
	Field216 float32 `dbc:"offset=216"`
	Field217 float32 `dbc:"offset=217"`
	Field218 float32 `dbc:"offset=218"`
	Field222 uint32 `dbc:"offset=222"`
	Field223 uint32 `dbc:"offset=223"`
	Field224 uint32 `dbc:"offset=224"`
	Field225 uint32 `dbc:"offset=225"`
	Field226 uint32 `dbc:"offset=226"`
	Field229 float32 `dbc:"offset=229"`
	Field230 float32 `dbc:"offset=230"`
	Field231 float32 `dbc:"offset=231"`
}

// SpellFocusObjectEntry represents the SpellFocusObject.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxx
type SpellFocusObjectEntry struct {
	ID uint32 `dbc:"offset=0"`
}

// SpellItemEnchantmentEntry represents the SpellItemEnchantment.dbc file structure.
//
// Format: niiiiiiixxxiiissssssssssssssssxiiiiiii
type SpellItemEnchantmentEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"` // string offset
	Field15 uint32 `dbc:"offset=15"` // string offset
	Field16 uint32 `dbc:"offset=16"` // string offset
	Field17 uint32 `dbc:"offset=17"` // string offset
	Field18 uint32 `dbc:"offset=18"` // string offset
	Field19 uint32 `dbc:"offset=19"` // string offset
	Field20 uint32 `dbc:"offset=20"` // string offset
	Field21 uint32 `dbc:"offset=21"` // string offset
	Field22 uint32 `dbc:"offset=22"` // string offset
	Field23 uint32 `dbc:"offset=23"` // string offset
	Field24 uint32 `dbc:"offset=24"` // string offset
	Field25 uint32 `dbc:"offset=25"` // string offset
	Field26 uint32 `dbc:"offset=26"` // string offset
	Field27 uint32 `dbc:"offset=27"` // string offset
	ItemDisplayInfoID uint32 `dbc:"offset=28"` // string offset
	Field29 uint32 `dbc:"offset=29"` // string offset
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
	Field35 uint32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Field37 uint32 `dbc:"offset=37"`
}

// SpellItemEnchantmentConditionEntry represents the SpellItemEnchantmentCondition.dbc file structure.
//
// Format: nbbbbbxxxxxbbbbbbbbbbiiiiiXXXXX
type SpellItemEnchantmentConditionEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 uint8 `dbc:"offset=1"`
	Field2 uint8 `dbc:"offset=2"`
	Field3 uint8 `dbc:"offset=3"`
	Field4 uint8 `dbc:"offset=4"`
	Field5 uint8 `dbc:"offset=5"`
	Field11 uint8 `dbc:"offset=11"`
	Field12 uint8 `dbc:"offset=12"`
	Field13 uint8 `dbc:"offset=13"`
	Field14 uint8 `dbc:"offset=14"`
	Field15 uint8 `dbc:"offset=15"`
	Field16 uint8 `dbc:"offset=16"`
	Field17 uint8 `dbc:"offset=17"`
	Field18 uint8 `dbc:"offset=18"`
	Field19 uint8 `dbc:"offset=19"`
	Field20 uint8 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
}

// SpellRadiusEntry represents the SpellRadius.dbc file structure.
//
// Format: nfff
type SpellRadiusEntry struct {
	ID uint32 `dbc:"offset=0"`
	RadiusMin float32 `dbc:"offset=1"`
	RadiusPerLevel float32 `dbc:"offset=2"`
	RadiusMax float32 `dbc:"offset=3"`
}

// SpellRangeEntry represents the SpellRange.dbc file structure.
//
// Format: nffffixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type SpellRangeEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
	Field2 float32 `dbc:"offset=2"`
	Field3 float32 `dbc:"offset=3"`
	Field4 float32 `dbc:"offset=4"`
	Flags uint32 `dbc:"offset=5"`
}

// SpellRuneCostEntry represents the SpellRuneCost.dbc file structure.
//
// Format: niiii
type SpellRuneCostEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	RunePowerGain uint32 `dbc:"offset=4"`
}

// SpellShapeshiftFormEntry represents the SpellShapeshiftForm.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxxiixiiixxiiiiiiii
type SpellShapeshiftFormEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field19 uint32 `dbc:"offset=19"`
	CreatureType uint32 `dbc:"offset=20"`
	AttackIcon uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
	Field30 uint32 `dbc:"offset=30"`
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
}

// SpellVisualEntry represents the SpellVisual.dbc file structure.
//
// Format: dxxxxxxiixxxxxxxxxxxxxxxxxxxxxxx
type SpellVisualEntry struct {
	ID uint32 `dbc:"offset=0"`
	PrecastKit uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
}

