// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// SpellCastTimeEntry represents the SpellCastTime.dbc file structure.
//
// Format: nixx
type SpellCastTimeEntry struct {
	ID uint32 `dbc:"offset=0"`
	CastTime uint32 `dbc:"offset=1"`
}

// SpellCategoryEntry represents the SpellCategory.dbc file structure.
//
// Format: ni
type SpellCategoryEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
}

// SpellDifficultyEntry represents the SpellDifficulty.dbc file structure.
//
// Format: niiii
type SpellDifficultyEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
}

// SpellDurationEntry represents the SpellDuration.dbc file structure.
//
// Format: niii
type SpellDurationEntry struct {
	ID uint32 `dbc:"offset=0"`
	Duration uint32 `dbc:"offset=1"`
	PerLevel uint32 `dbc:"offset=2"`
	MaxDuration uint32 `dbc:"offset=3"`
}

// SpellEntryEntry represents the SpellEntry.dbc file structure.
//
// Format: niiiiiiiiiiiixixiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifxiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssxssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxiiiiiiiiiiixfffxxxiiiiixxfffxx
type SpellEntryEntry struct {
	Id uint32 `dbc:"offset=0"`
	Category uint32 `dbc:"offset=1"`
	Dispel uint32 `dbc:"offset=2"`
	Mechanic uint32 `dbc:"offset=3"`
	Attributes uint32 `dbc:"offset=4"`
	AttributesEx uint32 `dbc:"offset=5"`
	AttributesEx2 uint32 `dbc:"offset=6"`
	AttributesEx3 uint32 `dbc:"offset=7"`
	AttributesEx4 uint32 `dbc:"offset=8"`
	AttributesEx5 uint32 `dbc:"offset=9"`
	AttributesEx6 uint32 `dbc:"offset=10"`
	AttributesEx7 uint32 `dbc:"offset=11"`
	Stances uint32 `dbc:"offset=12"`
	StancesNot uint32 `dbc:"offset=14"`
	Targets uint32 `dbc:"offset=16"`
	TargetCreatureType uint32 `dbc:"offset=17"`
	RequiresSpellFocus uint32 `dbc:"offset=18"`
	FacingCasterFlags uint32 `dbc:"offset=19"`
	CasterAuraState uint32 `dbc:"offset=20"`
	TargetAuraState uint32 `dbc:"offset=21"`
	CasterAuraStateNot uint32 `dbc:"offset=22"`
	TargetAuraStateNot uint32 `dbc:"offset=23"`
	CasterAuraSpell uint32 `dbc:"offset=24"`
	TargetAuraSpell uint32 `dbc:"offset=25"`
	ExcludeCasterAuraSpell uint32 `dbc:"offset=26"`
	ExcludeTargetAuraSpell uint32 `dbc:"offset=27"`
	CastingTimeIndex uint32 `dbc:"offset=28"`
	RecoveryTime uint32 `dbc:"offset=29"`
	CategoryRecoveryTime uint32 `dbc:"offset=30"`
	InterruptFlags uint32 `dbc:"offset=31"`
	AuraInterruptFlags uint32 `dbc:"offset=32"`
	ChannelInterruptFlags uint32 `dbc:"offset=33"`
	ProcFlags uint32 `dbc:"offset=34"`
	ProcChance uint32 `dbc:"offset=35"`
	ProcCharges uint32 `dbc:"offset=36"`
	MaxLevel uint32 `dbc:"offset=37"`
	BaseLevel uint32 `dbc:"offset=38"`
	SpellLevel uint32 `dbc:"offset=39"`
	DurationIndex uint32 `dbc:"offset=40"`
	PowerType uint32 `dbc:"offset=41"`
	ManaCost uint32 `dbc:"offset=42"`
	ManaCostPerlevel uint32 `dbc:"offset=43"`
	ManaPerSecond uint32 `dbc:"offset=44"`
	ManaPerSecondPerLevel uint32 `dbc:"offset=45"`
	RangeIndex uint32 `dbc:"offset=46"`
	Speed float32 `dbc:"offset=47"`
	StackAmount uint32 `dbc:"offset=49"`
	Totem0 uint32 `dbc:"offset=50"`
	Totem1 uint32 `dbc:"offset=51"`
	Reagent0 uint32 `dbc:"offset=52"`
	Reagent1 uint32 `dbc:"offset=53"`
	Reagent2 uint32 `dbc:"offset=54"`
	Reagent3 uint32 `dbc:"offset=55"`
	Reagent4 uint32 `dbc:"offset=56"`
	Reagent5 uint32 `dbc:"offset=57"`
	Reagent6 uint32 `dbc:"offset=58"`
	Reagent7 uint32 `dbc:"offset=59"`
	ReagentCount0 uint32 `dbc:"offset=60"`
	ReagentCount1 uint32 `dbc:"offset=61"`
	ReagentCount2 uint32 `dbc:"offset=62"`
	ReagentCount3 uint32 `dbc:"offset=63"`
	ReagentCount4 uint32 `dbc:"offset=64"`
	ReagentCount5 uint32 `dbc:"offset=65"`
	ReagentCount6 uint32 `dbc:"offset=66"`
	ReagentCount7 uint32 `dbc:"offset=67"`
	EquippedItemClass uint32 `dbc:"offset=68"`
	EquippedItemSubClassMask uint32 `dbc:"offset=69"`
	EquippedItemInventoryTypeMask uint32 `dbc:"offset=70"`
	Effect0 uint32 `dbc:"offset=71"`
	Effect1 uint32 `dbc:"offset=72"`
	Effect2 uint32 `dbc:"offset=73"`
	EffectDieSides0 uint32 `dbc:"offset=74"`
	EffectDieSides1 uint32 `dbc:"offset=75"`
	EffectDieSides2 uint32 `dbc:"offset=76"`
	EffectRealPointsPerLevel0 float32 `dbc:"offset=77"`
	EffectRealPointsPerLevel1 float32 `dbc:"offset=78"`
	EffectRealPointsPerLevel2 float32 `dbc:"offset=79"`
	EffectBasePoints0 uint32 `dbc:"offset=80"`
	EffectBasePoints1 uint32 `dbc:"offset=81"`
	EffectBasePoints2 uint32 `dbc:"offset=82"`
	EffectMechanic0 uint32 `dbc:"offset=83"`
	EffectMechanic1 uint32 `dbc:"offset=84"`
	EffectMechanic2 uint32 `dbc:"offset=85"`
	EffectImplicitTargetA0 uint32 `dbc:"offset=86"`
	EffectImplicitTargetA1 uint32 `dbc:"offset=87"`
	EffectImplicitTargetA2 uint32 `dbc:"offset=88"`
	EffectImplicitTargetB0 uint32 `dbc:"offset=89"`
	EffectImplicitTargetB1 uint32 `dbc:"offset=90"`
	EffectImplicitTargetB2 uint32 `dbc:"offset=91"`
	EffectRadiusIndex0 uint32 `dbc:"offset=92"`
	EffectRadiusIndex1 uint32 `dbc:"offset=93"`
	EffectRadiusIndex2 uint32 `dbc:"offset=94"`
	EffectApplyAuraName0 uint32 `dbc:"offset=95"`
	EffectApplyAuraName1 uint32 `dbc:"offset=96"`
	EffectApplyAuraName2 uint32 `dbc:"offset=97"`
	EffectAmplitude0 uint32 `dbc:"offset=98"`
	EffectAmplitude1 uint32 `dbc:"offset=99"`
	EffectAmplitude2 uint32 `dbc:"offset=100"`
	EffectValueMultiplier0 float32 `dbc:"offset=101"`
	EffectValueMultiplier1 float32 `dbc:"offset=102"`
	EffectValueMultiplier2 float32 `dbc:"offset=103"`
	EffectChainTarget0 uint32 `dbc:"offset=104"`
	EffectChainTarget1 uint32 `dbc:"offset=105"`
	EffectChainTarget2 uint32 `dbc:"offset=106"`
	EffectItemType0 uint32 `dbc:"offset=107"`
	EffectItemType1 uint32 `dbc:"offset=108"`
	EffectItemType2 uint32 `dbc:"offset=109"`
	EffectMiscValue0 uint32 `dbc:"offset=110"`
	EffectMiscValue1 uint32 `dbc:"offset=111"`
	EffectMiscValue2 uint32 `dbc:"offset=112"`
	EffectMiscValueB0 uint32 `dbc:"offset=113"`
	EffectMiscValueB1 uint32 `dbc:"offset=114"`
	EffectMiscValueB2 uint32 `dbc:"offset=115"`
	EffectTriggerSpell0 uint32 `dbc:"offset=116"`
	EffectTriggerSpell1 uint32 `dbc:"offset=117"`
	EffectTriggerSpell2 uint32 `dbc:"offset=118"`
	EffectPointsPerComboPoint0 float32 `dbc:"offset=119"`
	EffectPointsPerComboPoint1 float32 `dbc:"offset=120"`
	EffectPointsPerComboPoint2 float32 `dbc:"offset=121"`
	EffectSpellClassMask0_0 uint32 `dbc:"offset=122"`
	EffectSpellClassMask0_1 uint32 `dbc:"offset=123"`
	EffectSpellClassMask0_2 uint32 `dbc:"offset=124"`
	EffectSpellClassMask1_0 uint32 `dbc:"offset=125"`
	EffectSpellClassMask1_1 uint32 `dbc:"offset=126"`
	EffectSpellClassMask1_2 uint32 `dbc:"offset=127"`
	EffectSpellClassMask2_0 uint32 `dbc:"offset=128"`
	EffectSpellClassMask2_1 uint32 `dbc:"offset=129"`
	EffectSpellClassMask2_2 uint32 `dbc:"offset=130"`
	SpellVisual0 uint32 `dbc:"offset=131"`
	SpellVisual1 uint32 `dbc:"offset=132"`
	SpellIconID uint32 `dbc:"offset=133"`
	ActiveIconID uint32 `dbc:"offset=134"`
	SpellPriority uint32 `dbc:"offset=135"`
	Field136 LocalizedString `dbc:"offset=136"`
	Field153 LocalizedString `dbc:"offset=153"`
	ManaCostPercentage uint32 `dbc:"offset=204"`
	StartRecoveryCategory uint32 `dbc:"offset=205"`
	StartRecoveryTime uint32 `dbc:"offset=206"`
	MaxTargetLevel uint32 `dbc:"offset=207"`
	SpellFamilyName uint32 `dbc:"offset=208"`
	SpellFamilyFlags0 uint32 `dbc:"offset=209"`
	SpellFamilyFlags1 uint32 `dbc:"offset=210"`
	SpellFamilyFlags2 uint32 `dbc:"offset=211"`
	MaxAffectedTargets uint32 `dbc:"offset=212"`
	DmgClass uint32 `dbc:"offset=213"`
	PreventionType uint32 `dbc:"offset=214"`
	EffectDamageMultiplier0 float32 `dbc:"offset=216"`
	EffectDamageMultiplier1 float32 `dbc:"offset=217"`
	EffectDamageMultiplier2 float32 `dbc:"offset=218"`
	TotemCategory0 uint32 `dbc:"offset=222"`
	TotemCategory1 uint32 `dbc:"offset=223"`
	AreaGroupId uint32 `dbc:"offset=224"`
	SchoolMask uint32 `dbc:"offset=225"`
	RuneCostID uint32 `dbc:"offset=226"`
	EffectBonusMultiplier0 float32 `dbc:"offset=229"`
	EffectBonusMultiplier1 float32 `dbc:"offset=230"`
	EffectBonusMultiplier2 float32 `dbc:"offset=231"`
}

// SpellFocusObjectEntry represents the SpellFocusObject.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxx
type SpellFocusObjectEntry struct {
	ID uint32 `dbc:"offset=0"`
}

// SpellItemEnchantmentEntry represents the SpellItemEnchantment.dbc file structure.
//
// Format: niiiiiiixxxiiissssssssssssssssxiiiiiii
type SpellItemEnchantmentEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	Field4 uint32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"`
	Field6 uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"` // string offset
	Field15 uint32 `dbc:"offset=15"` // string offset
	Field16 uint32 `dbc:"offset=16"` // string offset
	Field17 uint32 `dbc:"offset=17"` // string offset
	Field18 uint32 `dbc:"offset=18"` // string offset
	Field19 uint32 `dbc:"offset=19"` // string offset
	Field20 uint32 `dbc:"offset=20"` // string offset
	Field21 uint32 `dbc:"offset=21"` // string offset
	Field22 uint32 `dbc:"offset=22"` // string offset
	Field23 uint32 `dbc:"offset=23"` // string offset
	Field24 uint32 `dbc:"offset=24"` // string offset
	Field25 uint32 `dbc:"offset=25"` // string offset
	Field26 uint32 `dbc:"offset=26"` // string offset
	Field27 uint32 `dbc:"offset=27"` // string offset
	ItemDisplayInfoID uint32 `dbc:"offset=28"` // string offset
	Field29 uint32 `dbc:"offset=29"` // string offset
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
	Field35 uint32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Field37 uint32 `dbc:"offset=37"`
}

// SpellItemEnchantmentConditionEntry represents the SpellItemEnchantmentCondition.dbc file structure.
//
// Format: nbbbbbxxxxxbbbbbbbbbbiiiiiXXXXX
type SpellItemEnchantmentConditionEntry struct {
	Index0 uint32 `dbc:"offset=0"`
	Field1 uint8 `dbc:"offset=1"`
	Field2 uint8 `dbc:"offset=2"`
	Field3 uint8 `dbc:"offset=3"`
	Field4 uint8 `dbc:"offset=4"`
	Field5 uint8 `dbc:"offset=5"`
	Field11 uint8 `dbc:"offset=11"`
	Field12 uint8 `dbc:"offset=12"`
	Field13 uint8 `dbc:"offset=13"`
	Field14 uint8 `dbc:"offset=14"`
	Field15 uint8 `dbc:"offset=15"`
	Field16 uint8 `dbc:"offset=16"`
	Field17 uint8 `dbc:"offset=17"`
	Field18 uint8 `dbc:"offset=18"`
	Field19 uint8 `dbc:"offset=19"`
	Field20 uint8 `dbc:"offset=20"`
	Field21 uint32 `dbc:"offset=21"`
	Field22 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field25 uint32 `dbc:"offset=25"`
}

// SpellRadiusEntry represents the SpellRadius.dbc file structure.
//
// Format: nfff
type SpellRadiusEntry struct {
	ID uint32 `dbc:"offset=0"`
	RadiusMin float32 `dbc:"offset=1"`
	RadiusPerLevel float32 `dbc:"offset=2"`
	RadiusMax float32 `dbc:"offset=3"`
}

// SpellRangeEntry represents the SpellRange.dbc file structure.
//
// Format: nffffixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
type SpellRangeEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 float32 `dbc:"offset=1"`
	Field2 float32 `dbc:"offset=2"`
	Field3 float32 `dbc:"offset=3"`
	Field4 float32 `dbc:"offset=4"`
	Flags uint32 `dbc:"offset=5"`
}

// SpellRuneCostEntry represents the SpellRuneCost.dbc file structure.
//
// Format: niiii
type SpellRuneCostEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field1 uint32 `dbc:"offset=1"`
	Field2 uint32 `dbc:"offset=2"`
	Field3 uint32 `dbc:"offset=3"`
	RunePowerGain uint32 `dbc:"offset=4"`
}

// SpellShapeshiftFormEntry represents the SpellShapeshiftForm.dbc file structure.
//
// Format: nxxxxxxxxxxxxxxxxxxiixiiixxiiiiiiii
type SpellShapeshiftFormEntry struct {
	ID uint32 `dbc:"offset=0"`
	Field19 uint32 `dbc:"offset=19"`
	CreatureType uint32 `dbc:"offset=20"`
	AttackIcon uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
	Field24 uint32 `dbc:"offset=24"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"`
	Field30 uint32 `dbc:"offset=30"`
	Field31 uint32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
}

// SpellVisualEntry represents the SpellVisual.dbc file structure.
//
// Format: dxxxxxxiixxxxxxxxxxxxxxxxxxxxxxx
type SpellVisualEntry struct {
	ID uint32 `dbc:"offset=0"`
	PrecastKit uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
}

