// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// TaxiNodesEntry represents the TaxiNodes.dbc file structure.
//
// Format: nifffssssssssssssssssxii
type TaxiNodesEntry struct {
	ID uint32 `dbc:"offset=0"`
	X uint32 `dbc:"offset=1"`
	Y float32 `dbc:"offset=2"`
	Z float32 `dbc:"offset=3"`
	Field4 float32 `dbc:"offset=4"`
	Field5 uint32 `dbc:"offset=5"` // string offset
	Field6 uint32 `dbc:"offset=6"` // string offset
	Field7 uint32 `dbc:"offset=7"` // string offset
	Field8 uint32 `dbc:"offset=8"` // string offset
	Field9 uint32 `dbc:"offset=9"` // string offset
	Field10 uint32 `dbc:"offset=10"` // string offset
	Field11 uint32 `dbc:"offset=11"` // string offset
	Field12 uint32 `dbc:"offset=12"` // string offset
	Field13 uint32 `dbc:"offset=13"` // string offset
	Field14 uint32 `dbc:"offset=14"` // string offset
	Field15 uint32 `dbc:"offset=15"` // string offset
	Field16 uint32 `dbc:"offset=16"` // string offset
	Field17 uint32 `dbc:"offset=17"` // string offset
	Field18 uint32 `dbc:"offset=18"` // string offset
	Field19 uint32 `dbc:"offset=19"` // string offset
	Field20 uint32 `dbc:"offset=20"` // string offset
	MountCreatureID2 uint32 `dbc:"offset=22"`
	Field23 uint32 `dbc:"offset=23"`
}

// TaxiPathEntry represents the TaxiPath.dbc file structure.
//
// Format: niii
type TaxiPathEntry struct {
	ID uint32 `dbc:"offset=0"`
	From uint32 `dbc:"offset=1"`
	To uint32 `dbc:"offset=2"`
	Price uint32 `dbc:"offset=3"`
}

// TaxiPathNodeEntry represents the TaxiPathNode.dbc file structure.
//
// Format: diiifffiiii
type TaxiPathNodeEntry struct {
	ID uint32 `dbc:"offset=0"`
	PathID uint32 `dbc:"offset=1"`
	NodeIndex uint32 `dbc:"offset=2"`
	MapID uint32 `dbc:"offset=3"`
	X float32 `dbc:"offset=4"`
	Y float32 `dbc:"offset=5"`
	Z float32 `dbc:"offset=6"`
	Delay uint32 `dbc:"offset=7"`
	ArriveEventID uint32 `dbc:"offset=8"`
	DepartEventID uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
}

