// Code generated by dbc-gen from AzerothCore DBCfmt.h. DO NOT EDIT!
//
// DBC file format for World of Warcraft 3.3.5a (WotLK).
// Each field uses a dbc tag specifying its column offset in the DBC record.
// LocalizedString fields occupy 16 columns (16 locale string offsets).
// *StringRef fields are single string offsets into the string block.

package wotlk

// VehicleEntry represents the Vehicle.dbc file structure.
//
// Format: niffffiiiiiiiifffffffffffffffssssfifiixx
type VehicleEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
	TurnSpeed float32 `dbc:"offset=2"`
	PitchSpeed float32 `dbc:"offset=3"`
	PitchMin float32 `dbc:"offset=4"`
	PitchMax float32 `dbc:"offset=5"`
	SeatID uint32 `dbc:"offset=6"`
	Field7 uint32 `dbc:"offset=7"`
	Field8 uint32 `dbc:"offset=8"`
	Field9 uint32 `dbc:"offset=9"`
	Field10 uint32 `dbc:"offset=10"`
	Field11 uint32 `dbc:"offset=11"`
	Field12 uint32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 float32 `dbc:"offset=14"`
	Field15 float32 `dbc:"offset=15"`
	Field16 float32 `dbc:"offset=16"`
	Field17 float32 `dbc:"offset=17"`
	Field18 float32 `dbc:"offset=18"`
	Field19 float32 `dbc:"offset=19"`
	Field20 float32 `dbc:"offset=20"`
	Field21 float32 `dbc:"offset=21"`
	Field22 float32 `dbc:"offset=22"`
	Field23 float32 `dbc:"offset=23"`
	Field24 float32 `dbc:"offset=24"`
	Field25 float32 `dbc:"offset=25"`
	Field26 float32 `dbc:"offset=26"`
	Field27 float32 `dbc:"offset=27"`
	Field28 float32 `dbc:"offset=28"`
	Field29 uint32 `dbc:"offset=29"` // string offset
	Field30 uint32 `dbc:"offset=30"` // string offset
	Field31 uint32 `dbc:"offset=31"` // string offset
	Field32 uint32 `dbc:"offset=32"` // string offset
	Field33 float32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
	Field35 float32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Field37 uint32 `dbc:"offset=37"`
}

// VehicleSeatEntry represents the VehicleSeat.dbc file structure.
//
// Format: niiffffffffffiiiiiifffffffiiifffiiiiiiiffiiiiixxxxxxxxxxxx
type VehicleSeatEntry struct {
	ID uint32 `dbc:"offset=0"`
	Flags uint32 `dbc:"offset=1"`
	AttachmentID uint32 `dbc:"offset=2"`
	AttachmentOffset float32 `dbc:"offset=3"`
	Field4 float32 `dbc:"offset=4"`
	Field5 float32 `dbc:"offset=5"`
	Field6 float32 `dbc:"offset=6"`
	Field7 float32 `dbc:"offset=7"`
	Field8 float32 `dbc:"offset=8"`
	Field9 float32 `dbc:"offset=9"`
	Field10 float32 `dbc:"offset=10"`
	Field11 float32 `dbc:"offset=11"`
	Field12 float32 `dbc:"offset=12"`
	Field13 uint32 `dbc:"offset=13"`
	Field14 uint32 `dbc:"offset=14"`
	Field15 uint32 `dbc:"offset=15"`
	Field16 uint32 `dbc:"offset=16"`
	Field17 uint32 `dbc:"offset=17"`
	Field18 uint32 `dbc:"offset=18"`
	Field19 float32 `dbc:"offset=19"`
	Field20 float32 `dbc:"offset=20"`
	Field21 float32 `dbc:"offset=21"`
	Field22 float32 `dbc:"offset=22"`
	Field23 float32 `dbc:"offset=23"`
	Field24 float32 `dbc:"offset=24"`
	Field25 float32 `dbc:"offset=25"`
	Field26 uint32 `dbc:"offset=26"`
	Field27 uint32 `dbc:"offset=27"`
	Field28 uint32 `dbc:"offset=28"`
	Field29 float32 `dbc:"offset=29"`
	Field30 float32 `dbc:"offset=30"`
	Field31 float32 `dbc:"offset=31"`
	Field32 uint32 `dbc:"offset=32"`
	Field33 uint32 `dbc:"offset=33"`
	Field34 uint32 `dbc:"offset=34"`
	Field35 uint32 `dbc:"offset=35"`
	Field36 uint32 `dbc:"offset=36"`
	Field37 uint32 `dbc:"offset=37"`
	Field38 uint32 `dbc:"offset=38"`
	Field39 float32 `dbc:"offset=39"`
	Field40 float32 `dbc:"offset=40"`
	Field41 uint32 `dbc:"offset=41"`
	Field42 uint32 `dbc:"offset=42"`
	Field43 uint32 `dbc:"offset=43"`
	Field44 uint32 `dbc:"offset=44"`
	Field45 uint32 `dbc:"offset=45"`
}

