// Code generated by handlergen. DO NOT EDIT.

package world

import (
    "github.com/paalgyula/summit/server/world/data/dynamic/interfaces"
    "github.com/paalgyula/summit/server/world/data/static"
    "github.com/paalgyula/summit/server/world/packet"
    "github.com/paalgyula/summit/server/world/packet/handlers"
    "github.com/paalgyula/summit/server/world/system"
)

var opCodeToHandler = map[static.OpCode]system.OpcodeHandler {
    {{range .Opcodes }}static.{{ .Packet }}: func(pkt interfaces.ClientPacket, state *system.State) ([]interfaces.ServerPacket, error) {
        return handlers.Handle{{ .Name }}(pkt.(*packet.{{ .Name }}), state)
    },
    {{end}}
}
