// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/paalgyula/summit/pkg/store (interfaces: AccountRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock_store/mock_account_repo.go -package=mock_store . AccountRepo
//

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	store "github.com/paalgyula/summit/pkg/store"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepo is a mock of AccountRepo interface.
type MockAccountRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepoMockRecorder
	isgomock struct{}
}

// MockAccountRepoMockRecorder is the mock recorder for MockAccountRepo.
type MockAccountRepoMockRecorder struct {
	mock *MockAccountRepo
}

// NewMockAccountRepo creates a new mock instance.
func NewMockAccountRepo(ctrl *gomock.Controller) *MockAccountRepo {
	mock := &MockAccountRepo{ctrl: ctrl}
	mock.recorder = &MockAccountRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepo) EXPECT() *MockAccountRepoMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountRepo) CreateAccount(account *store.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountRepoMockRecorder) CreateAccount(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountRepo)(nil).CreateAccount), account)
}

// FindAccount mocks base method.
func (m *MockAccountRepo) FindAccount(name string) *store.Account {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccount", name)
	ret0, _ := ret[0].(*store.Account)
	return ret0
}

// FindAccount indicates an expected call of FindAccount.
func (mr *MockAccountRepoMockRecorder) FindAccount(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccount", reflect.TypeOf((*MockAccountRepo)(nil).FindAccount), name)
}
