// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/paalgyula/summit/pkg/store (interfaces: WorldRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock_store/mock_world_repo.go -package=mock_store . WorldRepo
//

// Package mock_store is a generated GoMock package.
package mock_store

import (
	gomock "go.uber.org/mock/gomock"
)

// MockWorldRepo is a mock of WorldRepo interface.
type MockWorldRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorldRepoMockRecorder
	isgomock struct{}
}

// MockWorldRepoMockRecorder is the mock recorder for MockWorldRepo.
type MockWorldRepoMockRecorder struct {
	mock *MockWorldRepo
}

// NewMockWorldRepo creates a new mock instance.
func NewMockWorldRepo(ctrl *gomock.Controller) *MockWorldRepo {
	mock := &MockWorldRepo{ctrl: ctrl}
	mock.recorder = &MockWorldRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldRepo) EXPECT() *MockWorldRepoMockRecorder {
	return m.recorder
}
