// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/paalgyula/summit/pkg/store (interfaces: CharacterRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock_store/mock_character_repo.go -package=mock_store . CharacterRepo
//

// Package mock_store is a generated GoMock package.
package mock_store

import (
	reflect "reflect"

	player "github.com/paalgyula/summit/pkg/summit/world/object/player"
	gomock "go.uber.org/mock/gomock"
)

// MockCharacterRepo is a mock of CharacterRepo interface.
type MockCharacterRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCharacterRepoMockRecorder
	isgomock struct{}
}

// MockCharacterRepoMockRecorder is the mock recorder for MockCharacterRepo.
type MockCharacterRepoMockRecorder struct {
	mock *MockCharacterRepo
}

// NewMockCharacterRepo creates a new mock instance.
func NewMockCharacterRepo(ctrl *gomock.Controller) *MockCharacterRepo {
	mock := &MockCharacterRepo{ctrl: ctrl}
	mock.recorder = &MockCharacterRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharacterRepo) EXPECT() *MockCharacterRepoMockRecorder {
	return m.recorder
}

// CreateCharacter mocks base method.
func (m *MockCharacterRepo) CreateCharacter(account string, character *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCharacter", account, character)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCharacter indicates an expected call of CreateCharacter.
func (mr *MockCharacterRepoMockRecorder) CreateCharacter(account, character any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCharacter", reflect.TypeOf((*MockCharacterRepo)(nil).CreateCharacter), account, character)
}

// DeleteCharacter mocks base method.
func (m *MockCharacterRepo) DeleteCharacter(characterID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCharacter", characterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCharacter indicates an expected call of DeleteCharacter.
func (mr *MockCharacterRepoMockRecorder) DeleteCharacter(characterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCharacter", reflect.TypeOf((*MockCharacterRepo)(nil).DeleteCharacter), characterID)
}

// GetCharacter mocks base method.
func (m *MockCharacterRepo) GetCharacter(guid uint32) (*player.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacter", guid)
	ret0, _ := ret[0].(*player.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacter indicates an expected call of GetCharacter.
func (mr *MockCharacterRepoMockRecorder) GetCharacter(guid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacter", reflect.TypeOf((*MockCharacterRepo)(nil).GetCharacter), guid)
}

// GetCharacters mocks base method.
func (m *MockCharacterRepo) GetCharacters(account string) (player.Players, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCharacters", account)
	ret0, _ := ret[0].(player.Players)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCharacters indicates an expected call of GetCharacters.
func (mr *MockCharacterRepoMockRecorder) GetCharacters(account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCharacters", reflect.TypeOf((*MockCharacterRepo)(nil).GetCharacters), account)
}

// UpdateCharacter mocks base method.
func (m *MockCharacterRepo) UpdateCharacter(character *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCharacter", character)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCharacter indicates an expected call of UpdateCharacter.
func (mr *MockCharacterRepoMockRecorder) UpdateCharacter(character any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCharacter", reflect.TypeOf((*MockCharacterRepo)(nil).UpdateCharacter), character)
}

// UpdateCharacterQuests mocks base method.
func (m *MockCharacterRepo) UpdateCharacterQuests(character *player.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCharacterQuests", character)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCharacterQuests indicates an expected call of UpdateCharacterQuests.
func (mr *MockCharacterRepoMockRecorder) UpdateCharacterQuests(character any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCharacterQuests", reflect.TypeOf((*MockCharacterRepo)(nil).UpdateCharacterQuests), character)
}
