package world

import (
	"fmt"
	"net"
	"strings"

	"github.com/paalgyula/summit/pkg/summit/auth"
	"github.com/paalgyula/summit/pkg/summit/world/babysocket"
	"github.com/paalgyula/summit/pkg/summit/world/basedata"
	"github.com/paalgyula/summit/pkg/wow"
)

// ChatConfig holds configurable chat system settings.
type ChatConfig struct {
	// CrossFactionChat allows players of different factions to whisper
	// and use channels together. Enabled by default.
	CrossFactionChat bool

	// SayLevelReq is the minimum level required to use say/yell/emote.
	SayLevelReq int

	// WhisperLevelReq is the minimum level required to whisper.
	WhisperLevelReq int

	// ChatMuteFirstLogin mutes new players for ChatMuteMinutes on first login.
	ChatMuteFirstLogin bool
	ChatMuteMinutes    int

	// AddonChannel enables addon message traffic.
	AddonChannel bool
}

// DefaultChatConfig returns the default chat configuration.
// Cross-faction chat is enabled by default per user request.
func DefaultChatConfig() ChatConfig {
	return ChatConfig{
		CrossFactionChat:   true,
		SayLevelReq:        1,
		WhisperLevelReq:    10,
		ChatMuteFirstLogin: false,
		ChatMuteMinutes:    0,
		AddonChannel:       true,
	}
}

// Team returns 1 for Alliance races, 2 for Horde races.
func TeamFromRace(race wow.PlayerRace) int {
	switch race {
	case wow.RaceHuman, wow.RaceDwarf, wow.RaceNightElf, wow.RaceGnome, wow.RaceDraenei:
		return 1 // Alliance
	case wow.RaceOrc, wow.RaceUndead, wow.RaceTauren, wow.RaceTroll,
		wow.RaceGoblin, wow.RaceBloodElf:
		return 2 // Horde
	default:
		return 0 // neutral
	}
}

type ServerOption func(s *Server) error

// WithEndpoint sets the gameserver listen address. For example: 127.0.0.1:8129
func WithEndpoint(listenAddress string) ServerOption {
	return func(s *Server) error {
		listener, err := net.Listen("tcp", listenAddress)
		if err != nil {
			return fmt.Errorf("world.StartServer: %w", err)
		}

		s.gameListener = listener

		return nil
	}
}

// WithStaticBaseData loads the base data (starting positions and outfits,
// item templates) from summit.dat, generated by `datagen dbc`. Without it
// characters cannot be created and their equipment is not shown, so a missing
// file is logged, not fatal.
func WithStaticBaseData() ServerOption {
	return func(s *Server) error {
		data, err := basedata.LoadFromFile("summit.dat")
		if err != nil {
			s.log.Warn().Err(err).Msg("base data not loaded: run `datagen dbc` to generate summit.dat")

			return nil
		}

		s.baseData = data

		return nil
	}
}

// WithBabySocket can set the babysocket server if needed.
// It is socket based custom packet handler.
func WithBabySocket() ServerOption {
	return func(s *Server) error {
		bs, err := babysocket.NewServer("babysocket", s)
		if err != nil {
			return fmt.Errorf("world.StartServer: %w", err)
		}

		s.bs = bs

		return nil
	}
}

// WithAuthManagement set management service. There are two types:
//   - auth.ManagementClient: gRPC based (remote)
//   - auth.ManagementService: local implementation
func WithAuthManagement(ms auth.ManagementService) ServerOption {
	return func(s *Server) error {
		s.authManagement = ms

		return nil
	}
}

// WithSpellDBC loads spell data from DBC files in the given directory.
func WithSpellDBC(dbcPath string) ServerOption {
	return func(s *Server) error {
		if err := s.spellMgr.LoadSpells(dbcPath); err != nil {
			return fmt.Errorf("world.LoadSpells: %w", err)
		}

		return nil
	}
}

// WithChatConfig sets the chat system configuration.
func WithChatConfig(cfg ChatConfig) ServerOption {
	return func(s *Server) error {
		s.chatConfig = cfg

		return nil
	}
}

// IsAlliance returns true if the race belongs to the Alliance faction.
func IsAlliance(race wow.PlayerRace) bool {
	return TeamFromRace(race) == 1
}

// IsHorde returns true if the race belongs to the Horde faction.
func IsHorde(race wow.PlayerRace) bool {
	return TeamFromRace(race) == 2
}

// SameFaction returns true if two races belong to the same faction.
func SameFaction(race1, race2 wow.PlayerRace) bool {
	return TeamFromRace(race1) == TeamFromRace(race2)
}

// NormalizePlayerName capitalizes the first letter and lowercases the rest.
// WoW client sends player names with the first letter capitalized.
func NormalizePlayerName(name string) string {
	if len(name) == 0 {
		return name
	}

	return strings.ToUpper(name[:1]) + strings.ToLower(name[1:])
}
