package world

import (
	"fmt"
	"net"

	"github.com/paalgyula/summit/pkg/summit/auth"
	"github.com/paalgyula/summit/pkg/summit/world/babysocket"
	"github.com/paalgyula/summit/pkg/summit/world/basedata"
)

type ServerOption func(s *Server) error

// WithEndpoint sets the gameserver listen address. For example: 127.0.0.1:8129
func WithEndpoint(listenAddress string) ServerOption {
	return func(s *Server) error {
		listener, err := net.Listen("tcp", listenAddress)
		if err != nil {
			return fmt.Errorf("world.StartServer: %w", err)
		}

		s.gameListener = listener

		return nil
	}
}

// WithStaticBaseData loads the base data (starting positions and outfits,
// item templates) from summit.dat, generated by `datagen dbc`. Without it
// characters cannot be created and their equipment is not shown, so a missing
// file is logged, not fatal.
func WithStaticBaseData() ServerOption {
	return func(s *Server) error {
		data, err := basedata.LoadFromFile("summit.dat")
		if err != nil {
			s.log.Warn().Err(err).Msg("base data not loaded: run `datagen dbc` to generate summit.dat")

			return nil
		}

		s.baseData = data

		return nil
	}
}

// WithBabySocket can set the babysocket server if needed.
// The babysocket is socket based custom packet handler.
func WithBabySocket() ServerOption {
	return func(s *Server) error {
		bs, err := babysocket.NewServer("babysocket", s)
		if err != nil {
			return fmt.Errorf("world.StartServer: %w", err)
		}

		s.bs = bs

		return nil
	}
}

// WithAuthManagement set management service. There are two types:
//   - auth.ManagementClient: gRPC based (remote)
//   - auth.ManagementService: local implementation
func WithAuthManagement(ms auth.ManagementService) ServerOption {
	return func(s *Server) error {
		s.authManagement = ms

		return nil
	}
}

// WithSpellDBC loads spell data from DBC files in the given directory.
func WithSpellDBC(dbcPath string) ServerOption {
	return func(s *Server) error {
		if err := s.spellMgr.LoadSpells(dbcPath); err != nil {
			return fmt.Errorf("world.LoadSpells: %w", err)
		}

		return nil
	}
}
