// This file is generated! DO NOT EDIT!

package object

type UpdateField int

const (
	ObjectFieldGuid    UpdateField = 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	ObjectFieldType    UpdateField = 0x0002 // Size: 1 Type: INT Flags: PUBLIC
	ObjectFieldEntry   UpdateField = 0x0003 // Size: 1 Type: INT Flags: PUBLIC
	ObjectFieldScaleX  UpdateField = 0x0004 // Size: 1 Type: FLOAT Flags: PUBLIC
	ObjectFieldPadding UpdateField = 0x0005 // Size: 1 Type: INT Flags: NONE
)

const ObjectEnd = 0x0006

const (
	ItemFieldOwner              UpdateField = ObjectEnd + 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	ItemFieldContained          UpdateField = ObjectEnd + 0x0002 // Size: 2 Type: LONG Flags: PUBLIC
	ItemFieldCreator            UpdateField = ObjectEnd + 0x0004 // Size: 2 Type: LONG Flags: PUBLIC
	ItemFieldGiftcreator        UpdateField = ObjectEnd + 0x0006 // Size: 2 Type: LONG Flags: PUBLIC
	ItemFieldStackCount         UpdateField = ObjectEnd + 0x0008 // Size: 1 Type: INT Flags: OWNER ITEM_OWNER
	ItemFieldDuration           UpdateField = ObjectEnd + 0x0009 // Size: 1 Type: INT Flags: OWNER ITEM_OWNER
	ItemFieldSpellCharges       UpdateField = ObjectEnd + 0x000A // Size: 5 Type: INT Flags: OWNER ITEM_OWNER
	ItemFieldFlags              UpdateField = ObjectEnd + 0x000F // Size: 1 Type: INT Flags: PUBLIC
	ItemFieldEnchantment1_1     UpdateField = ObjectEnd + 0x0010 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment1_3     UpdateField = ObjectEnd + 0x0012 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment2_1     UpdateField = ObjectEnd + 0x0013 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment2_3     UpdateField = ObjectEnd + 0x0015 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment3_1     UpdateField = ObjectEnd + 0x0016 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment3_3     UpdateField = ObjectEnd + 0x0018 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment4_1     UpdateField = ObjectEnd + 0x0019 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment4_3     UpdateField = ObjectEnd + 0x001B // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment5_1     UpdateField = ObjectEnd + 0x001C // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment5_3     UpdateField = ObjectEnd + 0x001E // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment6_1     UpdateField = ObjectEnd + 0x001F // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment6_3     UpdateField = ObjectEnd + 0x0021 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment7_1     UpdateField = ObjectEnd + 0x0022 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment7_3     UpdateField = ObjectEnd + 0x0024 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment8_1     UpdateField = ObjectEnd + 0x0025 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment8_3     UpdateField = ObjectEnd + 0x0027 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment9_1     UpdateField = ObjectEnd + 0x0028 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment9_3     UpdateField = ObjectEnd + 0x002A // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment10_1    UpdateField = ObjectEnd + 0x002B // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment10_3    UpdateField = ObjectEnd + 0x002D // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment11_1    UpdateField = ObjectEnd + 0x002E // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment11_3    UpdateField = ObjectEnd + 0x0030 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldEnchantment12_1    UpdateField = ObjectEnd + 0x0031 // Size: 2 Type: INT Flags: PUBLIC
	ItemFieldEnchantment12_3    UpdateField = ObjectEnd + 0x0033 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	ItemFieldPropertySeed       UpdateField = ObjectEnd + 0x0034 // Size: 1 Type: INT Flags: PUBLIC
	ItemFieldRandomPropertiesId UpdateField = ObjectEnd + 0x0035 // Size: 1 Type: INT Flags: PUBLIC
	ItemFieldDurability         UpdateField = ObjectEnd + 0x0036 // Size: 1 Type: INT Flags: OWNER ITEM_OWNER
	ItemFieldMaxdurability      UpdateField = ObjectEnd + 0x0037 // Size: 1 Type: INT Flags: OWNER ITEM_OWNER
	ItemFieldCreatePlayedTime   UpdateField = ObjectEnd + 0x0038 // Size: 1 Type: INT Flags: PUBLIC
	ItemFieldPad                UpdateField = ObjectEnd + 0x0039 // Size: 1 Type: INT Flags: NONE
)

const ItemEnd = ObjectEnd + 0x003A

const (
	ContainerFieldNumSlots UpdateField = ItemEnd + 0x0000 // Size: 1 Type: INT Flags: PUBLIC
	ContainerAlignPad      UpdateField = ItemEnd + 0x0001 // Size: 1 Type: BYTES Flags: NONE
	ContainerFieldSlot_1   UpdateField = ItemEnd + 0x0002 // Size: 72 Type: LONG Flags: PUBLIC
)

const ContainerEnd = ItemEnd + 0x004A

const (
	UnitFieldCharm                             UpdateField = ObjectEnd + 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	UnitFieldSummon                            UpdateField = ObjectEnd + 0x0002 // Size: 2 Type: LONG Flags: PUBLIC
	UnitFieldCritter                           UpdateField = ObjectEnd + 0x0004 // Size: 2 Type: LONG Flags: PRIVATE
	UnitFieldCharmedby                         UpdateField = ObjectEnd + 0x0006 // Size: 2 Type: LONG Flags: PUBLIC
	UnitFieldSummonedby                        UpdateField = ObjectEnd + 0x0008 // Size: 2 Type: LONG Flags: PUBLIC
	UnitFieldCreatedby                         UpdateField = ObjectEnd + 0x000A // Size: 2 Type: LONG Flags: PUBLIC
	UnitFieldTarget                            UpdateField = ObjectEnd + 0x000C // Size: 2 Type: LONG Flags: PUBLIC
	UnitFieldChannelObject                     UpdateField = ObjectEnd + 0x000E // Size: 2 Type: LONG Flags: PUBLIC
	UnitChannelSpell                           UpdateField = ObjectEnd + 0x0010 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldBytes_0                           UpdateField = ObjectEnd + 0x0011 // Size: 1 Type: BYTES Flags: PUBLIC
	UnitFieldHealth                            UpdateField = ObjectEnd + 0x0012 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower1                            UpdateField = ObjectEnd + 0x0013 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower2                            UpdateField = ObjectEnd + 0x0014 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower3                            UpdateField = ObjectEnd + 0x0015 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower4                            UpdateField = ObjectEnd + 0x0016 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower5                            UpdateField = ObjectEnd + 0x0017 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower6                            UpdateField = ObjectEnd + 0x0018 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPower7                            UpdateField = ObjectEnd + 0x0019 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxhealth                         UpdateField = ObjectEnd + 0x001A // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower1                         UpdateField = ObjectEnd + 0x001B // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower2                         UpdateField = ObjectEnd + 0x001C // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower3                         UpdateField = ObjectEnd + 0x001D // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower4                         UpdateField = ObjectEnd + 0x001E // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower5                         UpdateField = ObjectEnd + 0x001F // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower6                         UpdateField = ObjectEnd + 0x0020 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMaxpower7                         UpdateField = ObjectEnd + 0x0021 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPowerRegenFlatModifier            UpdateField = ObjectEnd + 0x0022 // Size: 7 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldPowerRegenInterruptedFlatModifier UpdateField = ObjectEnd + 0x0029 // Size: 7 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldLevel                             UpdateField = ObjectEnd + 0x0030 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldFactiontemplate                   UpdateField = ObjectEnd + 0x0031 // Size: 1 Type: INT Flags: PUBLIC
	UnitVirtualItemSlotId                      UpdateField = ObjectEnd + 0x0032 // Size: 3 Type: INT Flags: PUBLIC
	UnitFieldFlags                             UpdateField = ObjectEnd + 0x0035 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldFlags_2                           UpdateField = ObjectEnd + 0x0036 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldAurastate                         UpdateField = ObjectEnd + 0x0037 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldBaseattacktime                    UpdateField = ObjectEnd + 0x0038 // Size: 2 Type: INT Flags: PUBLIC
	UnitFieldRangedattacktime                  UpdateField = ObjectEnd + 0x003A // Size: 1 Type: INT Flags: PRIVATE
	UnitFieldBoundingradius                    UpdateField = ObjectEnd + 0x003B // Size: 1 Type: FLOAT Flags: PUBLIC
	UnitFieldCombatreach                       UpdateField = ObjectEnd + 0x003C // Size: 1 Type: FLOAT Flags: PUBLIC
	UnitFieldDisplayid                         UpdateField = ObjectEnd + 0x003D // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldNativedisplayid                   UpdateField = ObjectEnd + 0x003E // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMountdisplayid                    UpdateField = ObjectEnd + 0x003F // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldMindamage                         UpdateField = ObjectEnd + 0x0040 // Size: 1 Type: FLOAT Flags: PRIVATE OWNER PARTY_LEADER
	UnitFieldMaxdamage                         UpdateField = ObjectEnd + 0x0041 // Size: 1 Type: FLOAT Flags: PRIVATE OWNER PARTY_LEADER
	UnitFieldMinoffhanddamage                  UpdateField = ObjectEnd + 0x0042 // Size: 1 Type: FLOAT Flags: PRIVATE OWNER PARTY_LEADER
	UnitFieldMaxoffhanddamage                  UpdateField = ObjectEnd + 0x0043 // Size: 1 Type: FLOAT Flags: PRIVATE OWNER PARTY_LEADER
	UnitFieldBytes_1                           UpdateField = ObjectEnd + 0x0044 // Size: 1 Type: BYTES Flags: PUBLIC
	UnitFieldPetnumber                         UpdateField = ObjectEnd + 0x0045 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPetNameTimestamp                  UpdateField = ObjectEnd + 0x0046 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldPetexperience                     UpdateField = ObjectEnd + 0x0047 // Size: 1 Type: INT Flags: OWNER
	UnitFieldPetnextlevelexp                   UpdateField = ObjectEnd + 0x0048 // Size: 1 Type: INT Flags: OWNER
	UnitDynamicFlags                           UpdateField = ObjectEnd + 0x0049 // Size: 1 Type: INT Flags: DYNAMIC
	UnitModCastSpeed                           UpdateField = ObjectEnd + 0x004A // Size: 1 Type: FLOAT Flags: PUBLIC
	UnitCreatedBySpell                         UpdateField = ObjectEnd + 0x004B // Size: 1 Type: INT Flags: PUBLIC
	UnitNpcFlags                               UpdateField = ObjectEnd + 0x004C // Size: 1 Type: INT Flags: DYNAMIC
	UnitNpcEmotestate                          UpdateField = ObjectEnd + 0x004D // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldStat0                             UpdateField = ObjectEnd + 0x004E // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldStat1                             UpdateField = ObjectEnd + 0x004F // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldStat2                             UpdateField = ObjectEnd + 0x0050 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldStat3                             UpdateField = ObjectEnd + 0x0051 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldStat4                             UpdateField = ObjectEnd + 0x0052 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldPosstat0                          UpdateField = ObjectEnd + 0x0053 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldPosstat1                          UpdateField = ObjectEnd + 0x0054 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldPosstat2                          UpdateField = ObjectEnd + 0x0055 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldPosstat3                          UpdateField = ObjectEnd + 0x0056 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldPosstat4                          UpdateField = ObjectEnd + 0x0057 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldNegstat0                          UpdateField = ObjectEnd + 0x0058 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldNegstat1                          UpdateField = ObjectEnd + 0x0059 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldNegstat2                          UpdateField = ObjectEnd + 0x005A // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldNegstat3                          UpdateField = ObjectEnd + 0x005B // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldNegstat4                          UpdateField = ObjectEnd + 0x005C // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldResistances                       UpdateField = ObjectEnd + 0x005D // Size: 7 Type: INT Flags: PRIVATE OWNER PARTY_LEADER
	UnitFieldResistancebuffmodspositive        UpdateField = ObjectEnd + 0x0064 // Size: 7 Type: INT Flags: PRIVATE OWNER
	UnitFieldResistancebuffmodsnegative        UpdateField = ObjectEnd + 0x006B // Size: 7 Type: INT Flags: PRIVATE OWNER
	UnitFieldBaseMana                          UpdateField = ObjectEnd + 0x0072 // Size: 1 Type: INT Flags: PUBLIC
	UnitFieldBaseHealth                        UpdateField = ObjectEnd + 0x0073 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldBytes_2                           UpdateField = ObjectEnd + 0x0074 // Size: 1 Type: BYTES Flags: PUBLIC
	UnitFieldAttackPower                       UpdateField = ObjectEnd + 0x0075 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldAttackPowerMods                   UpdateField = ObjectEnd + 0x0076 // Size: 1 Type: TWO_SHORT Flags: PRIVATE OWNER
	UnitFieldAttackPowerMultiplier             UpdateField = ObjectEnd + 0x0077 // Size: 1 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldRangedAttackPower                 UpdateField = ObjectEnd + 0x0078 // Size: 1 Type: INT Flags: PRIVATE OWNER
	UnitFieldRangedAttackPowerMods             UpdateField = ObjectEnd + 0x0079 // Size: 1 Type: TWO_SHORT Flags: PRIVATE OWNER
	UnitFieldRangedAttackPowerMultiplier       UpdateField = ObjectEnd + 0x007A // Size: 1 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldMinrangeddamage                   UpdateField = ObjectEnd + 0x007B // Size: 1 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldMaxrangeddamage                   UpdateField = ObjectEnd + 0x007C // Size: 1 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldPowerCostModifier                 UpdateField = ObjectEnd + 0x007D // Size: 7 Type: INT Flags: PRIVATE OWNER
	UnitFieldPowerCostMultiplier               UpdateField = ObjectEnd + 0x0084 // Size: 7 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldMaxhealthmodifier                 UpdateField = ObjectEnd + 0x008B // Size: 1 Type: FLOAT Flags: PRIVATE OWNER
	UnitFieldHoverheight                       UpdateField = ObjectEnd + 0x008C // Size: 1 Type: FLOAT Flags: PUBLIC
	UnitFieldPadding                           UpdateField = ObjectEnd + 0x008D // Size: 1 Type: INT Flags: NONE
	UnitEnd                                    UpdateField = ObjectEnd + 0x008E
	PlayerDuelArbiter                          UpdateField = UnitEnd + 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	PlayerFlags                                UpdateField = UnitEnd + 0x0002 // Size: 1 Type: INT Flags: PUBLIC
	PlayerGuildid                              UpdateField = UnitEnd + 0x0003 // Size: 1 Type: INT Flags: PUBLIC
	PlayerGuildrank                            UpdateField = UnitEnd + 0x0004 // Size: 1 Type: INT Flags: PUBLIC
	PlayerBytes                                UpdateField = UnitEnd + 0x0005 // Size: 1 Type: BYTES Flags: PUBLIC
	PlayerBytes_2                              UpdateField = UnitEnd + 0x0006 // Size: 1 Type: BYTES Flags: PUBLIC
	PlayerBytes_3                              UpdateField = UnitEnd + 0x0007 // Size: 1 Type: BYTES Flags: PUBLIC
	PlayerDuelTeam                             UpdateField = UnitEnd + 0x0008 // Size: 1 Type: INT Flags: PUBLIC
	PlayerGuildTimestamp                       UpdateField = UnitEnd + 0x0009 // Size: 1 Type: INT Flags: PUBLIC
	PlayerQuestLog1_1                          UpdateField = UnitEnd + 0x000A // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog1_2                          UpdateField = UnitEnd + 0x000B // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog1_3                          UpdateField = UnitEnd + 0x000C // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog1_4                          UpdateField = UnitEnd + 0x000E // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog2_1                          UpdateField = UnitEnd + 0x000F // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog2_2                          UpdateField = UnitEnd + 0x0010 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog2_3                          UpdateField = UnitEnd + 0x0011 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog2_5                          UpdateField = UnitEnd + 0x0013 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog3_1                          UpdateField = UnitEnd + 0x0014 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog3_2                          UpdateField = UnitEnd + 0x0015 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog3_3                          UpdateField = UnitEnd + 0x0016 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog3_5                          UpdateField = UnitEnd + 0x0018 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog4_1                          UpdateField = UnitEnd + 0x0019 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog4_2                          UpdateField = UnitEnd + 0x001A // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog4_3                          UpdateField = UnitEnd + 0x001B // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog4_5                          UpdateField = UnitEnd + 0x001D // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog5_1                          UpdateField = UnitEnd + 0x001E // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog5_2                          UpdateField = UnitEnd + 0x001F // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog5_3                          UpdateField = UnitEnd + 0x0020 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog5_5                          UpdateField = UnitEnd + 0x0022 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog6_1                          UpdateField = UnitEnd + 0x0023 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog6_2                          UpdateField = UnitEnd + 0x0024 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog6_3                          UpdateField = UnitEnd + 0x0025 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog6_5                          UpdateField = UnitEnd + 0x0027 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog7_1                          UpdateField = UnitEnd + 0x0028 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog7_2                          UpdateField = UnitEnd + 0x0029 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog7_3                          UpdateField = UnitEnd + 0x002A // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog7_5                          UpdateField = UnitEnd + 0x002C // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog8_1                          UpdateField = UnitEnd + 0x002D // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog8_2                          UpdateField = UnitEnd + 0x002E // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog8_3                          UpdateField = UnitEnd + 0x002F // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog8_5                          UpdateField = UnitEnd + 0x0031 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog9_1                          UpdateField = UnitEnd + 0x0032 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog9_2                          UpdateField = UnitEnd + 0x0033 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog9_3                          UpdateField = UnitEnd + 0x0034 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog9_5                          UpdateField = UnitEnd + 0x0036 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog10_1                         UpdateField = UnitEnd + 0x0037 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog10_2                         UpdateField = UnitEnd + 0x0038 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog10_3                         UpdateField = UnitEnd + 0x0039 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog10_5                         UpdateField = UnitEnd + 0x003B // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog11_1                         UpdateField = UnitEnd + 0x003C // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog11_2                         UpdateField = UnitEnd + 0x003D // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog11_3                         UpdateField = UnitEnd + 0x003E // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog11_5                         UpdateField = UnitEnd + 0x0040 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog12_1                         UpdateField = UnitEnd + 0x0041 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog12_2                         UpdateField = UnitEnd + 0x0042 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog12_3                         UpdateField = UnitEnd + 0x0043 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog12_5                         UpdateField = UnitEnd + 0x0045 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog13_1                         UpdateField = UnitEnd + 0x0046 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog13_2                         UpdateField = UnitEnd + 0x0047 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog13_3                         UpdateField = UnitEnd + 0x0048 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog13_5                         UpdateField = UnitEnd + 0x004A // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog14_1                         UpdateField = UnitEnd + 0x004B // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog14_2                         UpdateField = UnitEnd + 0x004C // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog14_3                         UpdateField = UnitEnd + 0x004D // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog14_5                         UpdateField = UnitEnd + 0x004F // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog15_1                         UpdateField = UnitEnd + 0x0050 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog15_2                         UpdateField = UnitEnd + 0x0051 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog15_3                         UpdateField = UnitEnd + 0x0052 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog15_5                         UpdateField = UnitEnd + 0x0054 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog16_1                         UpdateField = UnitEnd + 0x0055 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog16_2                         UpdateField = UnitEnd + 0x0056 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog16_3                         UpdateField = UnitEnd + 0x0057 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog16_5                         UpdateField = UnitEnd + 0x0059 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog17_1                         UpdateField = UnitEnd + 0x005A // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog17_2                         UpdateField = UnitEnd + 0x005B // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog17_3                         UpdateField = UnitEnd + 0x005C // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog17_5                         UpdateField = UnitEnd + 0x005E // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog18_1                         UpdateField = UnitEnd + 0x005F // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog18_2                         UpdateField = UnitEnd + 0x0060 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog18_3                         UpdateField = UnitEnd + 0x0061 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog18_5                         UpdateField = UnitEnd + 0x0063 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog19_1                         UpdateField = UnitEnd + 0x0064 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog19_2                         UpdateField = UnitEnd + 0x0065 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog19_3                         UpdateField = UnitEnd + 0x0066 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog19_5                         UpdateField = UnitEnd + 0x0068 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog20_1                         UpdateField = UnitEnd + 0x0069 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog20_2                         UpdateField = UnitEnd + 0x006A // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog20_3                         UpdateField = UnitEnd + 0x006B // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog20_5                         UpdateField = UnitEnd + 0x006D // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog21_1                         UpdateField = UnitEnd + 0x006E // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog21_2                         UpdateField = UnitEnd + 0x006F // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog21_3                         UpdateField = UnitEnd + 0x0070 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog21_5                         UpdateField = UnitEnd + 0x0072 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog22_1                         UpdateField = UnitEnd + 0x0073 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog22_2                         UpdateField = UnitEnd + 0x0074 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog22_3                         UpdateField = UnitEnd + 0x0075 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog22_5                         UpdateField = UnitEnd + 0x0077 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog23_1                         UpdateField = UnitEnd + 0x0078 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog23_2                         UpdateField = UnitEnd + 0x0079 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog23_3                         UpdateField = UnitEnd + 0x007A // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog23_5                         UpdateField = UnitEnd + 0x007C // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog24_1                         UpdateField = UnitEnd + 0x007D // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog24_2                         UpdateField = UnitEnd + 0x007E // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog24_3                         UpdateField = UnitEnd + 0x007F // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog24_5                         UpdateField = UnitEnd + 0x0081 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog25_1                         UpdateField = UnitEnd + 0x0082 // Size: 1 Type: INT Flags: PARTY_MEMBER
	PlayerQuestLog25_2                         UpdateField = UnitEnd + 0x0083 // Size: 1 Type: INT Flags: PRIVATE
	PlayerQuestLog25_3                         UpdateField = UnitEnd + 0x0084 // Size: 2 Type: TWO_SHORT Flags: PRIVATE
	PlayerQuestLog25_5                         UpdateField = UnitEnd + 0x0086 // Size: 1 Type: INT Flags: PRIVATE
	PlayerVisibleItem1Entryid                  UpdateField = UnitEnd + 0x0087 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem1Enchantment              UpdateField = UnitEnd + 0x0088 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem2Entryid                  UpdateField = UnitEnd + 0x0089 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem2Enchantment              UpdateField = UnitEnd + 0x008A // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem3Entryid                  UpdateField = UnitEnd + 0x008B // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem3Enchantment              UpdateField = UnitEnd + 0x008C // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem4Entryid                  UpdateField = UnitEnd + 0x008D // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem4Enchantment              UpdateField = UnitEnd + 0x008E // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem5Entryid                  UpdateField = UnitEnd + 0x008F // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem5Enchantment              UpdateField = UnitEnd + 0x0090 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem6Entryid                  UpdateField = UnitEnd + 0x0091 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem6Enchantment              UpdateField = UnitEnd + 0x0092 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem7Entryid                  UpdateField = UnitEnd + 0x0093 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem7Enchantment              UpdateField = UnitEnd + 0x0094 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem8Entryid                  UpdateField = UnitEnd + 0x0095 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem8Enchantment              UpdateField = UnitEnd + 0x0096 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem9Entryid                  UpdateField = UnitEnd + 0x0097 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem9Enchantment              UpdateField = UnitEnd + 0x0098 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem10Entryid                 UpdateField = UnitEnd + 0x0099 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem10Enchantment             UpdateField = UnitEnd + 0x009A // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem11Entryid                 UpdateField = UnitEnd + 0x009B // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem11Enchantment             UpdateField = UnitEnd + 0x009C // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem12Entryid                 UpdateField = UnitEnd + 0x009D // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem12Enchantment             UpdateField = UnitEnd + 0x009E // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem13Entryid                 UpdateField = UnitEnd + 0x009F // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem13Enchantment             UpdateField = UnitEnd + 0x00A0 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem14Entryid                 UpdateField = UnitEnd + 0x00A1 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem14Enchantment             UpdateField = UnitEnd + 0x00A2 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem15Entryid                 UpdateField = UnitEnd + 0x00A3 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem15Enchantment             UpdateField = UnitEnd + 0x00A4 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem16Entryid                 UpdateField = UnitEnd + 0x00A5 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem16Enchantment             UpdateField = UnitEnd + 0x00A6 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem17Entryid                 UpdateField = UnitEnd + 0x00A7 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem17Enchantment             UpdateField = UnitEnd + 0x00A8 // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem18Entryid                 UpdateField = UnitEnd + 0x00A9 // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem18Enchantment             UpdateField = UnitEnd + 0x00AA // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerVisibleItem19Entryid                 UpdateField = UnitEnd + 0x00AB // Size: 1 Type: INT Flags: PUBLIC
	PlayerVisibleItem19Enchantment             UpdateField = UnitEnd + 0x00AC // Size: 1 Type: TWO_SHORT Flags: PUBLIC
	PlayerChosenTitle                          UpdateField = UnitEnd + 0x00AD // Size: 1 Type: INT Flags: PUBLIC
	PlayerFakeInebriation                      UpdateField = UnitEnd + 0x00AE // Size: 1 Type: INT Flags: PUBLIC
	PlayerFieldPad_0                           UpdateField = UnitEnd + 0x00AF // Size: 1 Type: INT Flags: NONE
	PlayerFieldInvSlotHead                     UpdateField = UnitEnd + 0x00B0 // Size: 46 Type: LONG Flags: PRIVATE
	PlayerFieldPackSlot_1                      UpdateField = UnitEnd + 0x00DE // Size: 32 Type: LONG Flags: PRIVATE
	PlayerFieldBankSlot_1                      UpdateField = UnitEnd + 0x00FE // Size: 56 Type: LONG Flags: PRIVATE
	PlayerFieldBankbagSlot_1                   UpdateField = UnitEnd + 0x0136 // Size: 14 Type: LONG Flags: PRIVATE
	PlayerFieldVendorbuybackSlot_1             UpdateField = UnitEnd + 0x0144 // Size: 24 Type: LONG Flags: PRIVATE
	PlayerFieldKeyringSlot_1                   UpdateField = UnitEnd + 0x015C // Size: 64 Type: LONG Flags: PRIVATE
	PlayerFieldCurrencytokenSlot_1             UpdateField = UnitEnd + 0x019C // Size: 64 Type: LONG Flags: PRIVATE
	PlayerFarsight                             UpdateField = UnitEnd + 0x01DC // Size: 2 Type: LONG Flags: PRIVATE
	PlayerFieldKnownTitles                     UpdateField = UnitEnd + 0x01DE // Size: 2 Type: LONG Flags: PRIVATE
	PlayerFieldKnownTitles1                    UpdateField = UnitEnd + 0x01E0 // Size: 2 Type: LONG Flags: PRIVATE
	PlayerFieldKnownTitles2                    UpdateField = UnitEnd + 0x01E2 // Size: 2 Type: LONG Flags: PRIVATE
	PlayerFieldKnownCurrencies                 UpdateField = UnitEnd + 0x01E4 // Size: 2 Type: LONG Flags: PRIVATE
	PlayerXp                                   UpdateField = UnitEnd + 0x01E6 // Size: 1 Type: INT Flags: PRIVATE
	PlayerNextLevelXp                          UpdateField = UnitEnd + 0x01E7 // Size: 1 Type: INT Flags: PRIVATE
	PlayerSkillInfo1_1                         UpdateField = UnitEnd + 0x01E8 // Size: 384 Type: TWO_SHORT Flags: PRIVATE
	PlayerCharacterPoints1                     UpdateField = UnitEnd + 0x0368 // Size: 1 Type: INT Flags: PRIVATE
	PlayerCharacterPoints2                     UpdateField = UnitEnd + 0x0369 // Size: 1 Type: INT Flags: PRIVATE
	PlayerTrackCreatures                       UpdateField = UnitEnd + 0x036A // Size: 1 Type: INT Flags: PRIVATE
	PlayerTrackResources                       UpdateField = UnitEnd + 0x036B // Size: 1 Type: INT Flags: PRIVATE
	PlayerBlockPercentage                      UpdateField = UnitEnd + 0x036C // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerDodgePercentage                      UpdateField = UnitEnd + 0x036D // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerParryPercentage                      UpdateField = UnitEnd + 0x036E // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerExpertise                            UpdateField = UnitEnd + 0x036F // Size: 1 Type: INT Flags: PRIVATE
	PlayerOffhandExpertise                     UpdateField = UnitEnd + 0x0370 // Size: 1 Type: INT Flags: PRIVATE
	PlayerCritPercentage                       UpdateField = UnitEnd + 0x0371 // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerRangedCritPercentage                 UpdateField = UnitEnd + 0x0372 // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerOffhandCritPercentage                UpdateField = UnitEnd + 0x0373 // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerSpellCritPercentage1                 UpdateField = UnitEnd + 0x0374 // Size: 7 Type: FLOAT Flags: PRIVATE
	PlayerShieldBlock                          UpdateField = UnitEnd + 0x037B // Size: 1 Type: INT Flags: PRIVATE
	PlayerShieldBlockCritPercentage            UpdateField = UnitEnd + 0x037C // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerExploredZones_1                      UpdateField = UnitEnd + 0x037D // Size: 128 Type: BYTES Flags: PRIVATE
	PlayerRestStateExperience                  UpdateField = UnitEnd + 0x03FD // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldCoinage                         UpdateField = UnitEnd + 0x03FE // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldModDamageDonePos                UpdateField = UnitEnd + 0x03FF // Size: 7 Type: INT Flags: PRIVATE
	PlayerFieldModDamageDoneNeg                UpdateField = UnitEnd + 0x0406 // Size: 7 Type: INT Flags: PRIVATE
	PlayerFieldModDamageDonePct                UpdateField = UnitEnd + 0x040D // Size: 7 Type: INT Flags: PRIVATE
	PlayerFieldModHealingDonePos               UpdateField = UnitEnd + 0x0414 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldModHealingPct                   UpdateField = UnitEnd + 0x0415 // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerFieldModHealingDonePct               UpdateField = UnitEnd + 0x0416 // Size: 1 Type: FLOAT Flags: PRIVATE
	PlayerFieldModTargetResistance             UpdateField = UnitEnd + 0x0417 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldModTargetPhysicalResistance     UpdateField = UnitEnd + 0x0418 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldBytes                           UpdateField = UnitEnd + 0x0419 // Size: 1 Type: BYTES Flags: PRIVATE
	PlayerAmmoId                               UpdateField = UnitEnd + 0x041A // Size: 1 Type: INT Flags: PRIVATE
	PlayerSelfResSpell                         UpdateField = UnitEnd + 0x041B // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldPvpMedals                       UpdateField = UnitEnd + 0x041C // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldBuybackPrice_1                  UpdateField = UnitEnd + 0x041D // Size: 12 Type: INT Flags: PRIVATE
	PlayerFieldBuybackTimestamp_1              UpdateField = UnitEnd + 0x0429 // Size: 12 Type: INT Flags: PRIVATE
	PlayerFieldKills                           UpdateField = UnitEnd + 0x0435 // Size: 1 Type: TWO_SHORT Flags: PRIVATE
	PlayerFieldTodayContribution               UpdateField = UnitEnd + 0x0436 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldYesterdayContribution           UpdateField = UnitEnd + 0x0437 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldLifetimeHonorableKills          UpdateField = UnitEnd + 0x0438 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldBytes2                          UpdateField = UnitEnd + 0x0439 // Size: 1 Type: 6 Flags: PRIVATE
	PlayerFieldWatchedFactionIndex             UpdateField = UnitEnd + 0x043A // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldCombatRating_1                  UpdateField = UnitEnd + 0x043B // Size: 25 Type: INT Flags: PRIVATE
	PlayerFieldArenaTeamInfo1_1                UpdateField = UnitEnd + 0x0454 // Size: 21 Type: INT Flags: PRIVATE
	PlayerFieldHonorCurrency                   UpdateField = UnitEnd + 0x0469 // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldArenaCurrency                   UpdateField = UnitEnd + 0x046A // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldMaxLevel                        UpdateField = UnitEnd + 0x046B // Size: 1 Type: INT Flags: PRIVATE
	PlayerFieldDailyQuests_1                   UpdateField = UnitEnd + 0x046C // Size: 25 Type: INT Flags: PRIVATE
	PlayerRuneRegen_1                          UpdateField = UnitEnd + 0x0485 // Size: 4 Type: FLOAT Flags: PRIVATE
	PlayerNoReagentCost_1                      UpdateField = UnitEnd + 0x0489 // Size: 3 Type: INT Flags: PRIVATE
	PlayerFieldGlyphSlots_1                    UpdateField = UnitEnd + 0x048C // Size: 6 Type: INT Flags: PRIVATE
	PlayerFieldGlyphs_1                        UpdateField = UnitEnd + 0x0492 // Size: 6 Type: INT Flags: PRIVATE
	PlayerGlyphsEnabled                        UpdateField = UnitEnd + 0x0498 // Size: 1 Type: INT Flags: PRIVATE
	PlayerPetSpellPower                        UpdateField = UnitEnd + 0x0499 // Size: 1 Type: INT Flags: PRIVATE
)

const PlayerEnd = UnitEnd + 0x049A

const (
	ObjectFieldCreatedBy     UpdateField = ObjectEnd + 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	GameobjectDisplayid      UpdateField = ObjectEnd + 0x0002 // Size: 1 Type: INT Flags: PUBLIC
	GameobjectFlags          UpdateField = ObjectEnd + 0x0003 // Size: 1 Type: INT Flags: PUBLIC
	GameobjectParentrotation UpdateField = ObjectEnd + 0x0004 // Size: 4 Type: FLOAT Flags: PUBLIC
	GameobjectDynamic        UpdateField = ObjectEnd + 0x0008 // Size: 1 Type: TWO_SHORT Flags: DYNAMIC
	GameobjectFaction        UpdateField = ObjectEnd + 0x0009 // Size: 1 Type: INT Flags: PUBLIC
	GameobjectLevel          UpdateField = ObjectEnd + 0x000A // Size: 1 Type: INT Flags: PUBLIC
	GameobjectBytes_1        UpdateField = ObjectEnd + 0x000B // Size: 1 Type: BYTES Flags: PUBLIC
)

const GameobjectEnd = ObjectEnd + 0x000C

const (
	DynamicobjectCaster   UpdateField = ObjectEnd + 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	DynamicobjectBytes    UpdateField = ObjectEnd + 0x0002 // Size: 1 Type: BYTES Flags: PUBLIC
	DynamicobjectSpellid  UpdateField = ObjectEnd + 0x0003 // Size: 1 Type: INT Flags: PUBLIC
	DynamicobjectRadius   UpdateField = ObjectEnd + 0x0004 // Size: 1 Type: FLOAT Flags: PUBLIC
	DynamicobjectCasttime UpdateField = ObjectEnd + 0x0005 // Size: 1 Type: INT Flags: PUBLIC
)

const DynamicobjectEnd = ObjectEnd + 0x0006

const (
	CorpseFieldOwner        UpdateField = ObjectEnd + 0x0000 // Size: 2 Type: LONG Flags: PUBLIC
	CorpseFieldParty        UpdateField = ObjectEnd + 0x0002 // Size: 2 Type: LONG Flags: PUBLIC
	CorpseFieldDisplayId    UpdateField = ObjectEnd + 0x0004 // Size: 1 Type: INT Flags: PUBLIC
	CorpseFieldItem         UpdateField = ObjectEnd + 0x0005 // Size: 19 Type: INT Flags: PUBLIC
	CorpseFieldBytes_1      UpdateField = ObjectEnd + 0x0018 // Size: 1 Type: BYTES Flags: PUBLIC
	CorpseFieldBytes_2      UpdateField = ObjectEnd + 0x0019 // Size: 1 Type: BYTES Flags: PUBLIC
	CorpseFieldGuild        UpdateField = ObjectEnd + 0x001A // Size: 1 Type: INT Flags: PUBLIC
	CorpseFieldFlags        UpdateField = ObjectEnd + 0x001B // Size: 1 Type: INT Flags: PUBLIC
	CorpseFieldDynamicFlags UpdateField = ObjectEnd + 0x001C // Size: 1 Type: INT Flags: DYNAMIC
	CorpseFieldPad          UpdateField = ObjectEnd + 0x001D // Size: 1 Type: INT Flags: NONE
)

const CorpseEnd = ObjectEnd + 0x001E
