// Code generated by "stringer -type=AuthCmd"; DO NOT EDIT.

package packets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthLoginChallenge-0]
	_ = x[AuthLoginProof-1]
	_ = x[AuthReconnectChallenge-2]
	_ = x[AuthReconnectProof-3]
	_ = x[RealmList-16]
}

const (
	_AuthCmd_name_0 = "AuthLoginChallengeAuthLoginProofAuthReconnectChallengeAuthReconnectProof"
	_AuthCmd_name_1 = "RealmList"
)

var (
	_AuthCmd_index_0 = [...]uint8{0, 18, 32, 54, 72}
)

func (i AuthCmd) String() string {
	switch {
	case i <= 3:
		return _AuthCmd_name_0[_AuthCmd_index_0[i]:_AuthCmd_index_0[i+1]]
	case i == 16:
		return _AuthCmd_name_1
	default:
		return "AuthCmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
